<?php
// Rebuild the legacy constant packs after updating translations.tsv or English files.
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
require_once __DIR__.'/../include/lanai/localization.php';
$root = dirname(__DIR__);
$sources = array_merge(array(__DIR__.'/lang-english.php'), glob($root.'/modules/*/language/lang-english.php'), array($root.'/install/language/lang-english.php'));
$count = 0;
foreach ($sources as $source) {
    preg_match_all('/define\(\s*"([A-Z_0-9]+)"\s*,\s*"((?:\\\\.|[^"\\\\])*)"\s*\)\s*;/', file_get_contents($source), $matches, PREG_SET_ORDER);
    foreach (array_diff(array_keys(lanai_languages()), array('english','thai')) as $language) {
        $output = "<?php\n// Generated by language/build-packs.php; edit language/translations.tsv.\n";
        foreach ($matches as $match) {
            $value = lanai_translate(stripcslashes($match[2]), $language);
            $output .= 'if (!defined('.var_export($match[1], true).')) define('.var_export($match[1], true).', '.var_export($value, true).");\n";
        }
        if (file_put_contents(str_replace('lang-english.php', 'lang-'.$language.'.php', $source), $output) === false) throw new RuntimeException('Could not write language pack.');
        $count++;
    }
}
echo "Generated $count language files.\n";
