<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_INFO_SETTING')) define('_INFO_SETTING', 'Produktinformationen');
if (!defined('_INFO_SETTING_INSTRUCTION')) define('_INFO_SETTING_INSTRUCTION', 'Prüfen Sie Produktinformationen, Version und Lizenz.');
if (!defined('_INFO')) define('_INFO', 'Informationen');
if (!defined('_LICENSE')) define('_LICENSE', 'Lizenz');
if (!defined('_LICENSE_UNAVAILABLE')) define('_LICENSE_UNAVAILABLE', 'Der Lizenztext ist derzeit nicht verfügbar.');
if (!defined('_CREDIT')) define('_CREDIT', 'Mitwirkende');
if (!defined('_VERSION')) define('_VERSION', 'Version');
if (!defined('_SERIAL')) define('_SERIAL', 'Seriennummer');
if (!defined('_LICENSED_TO')) define('_LICENSED_TO', 'Lizenziert für');
if (!defined('_REGISTER_THIS_PRODUCT')) define('_REGISTER_THIS_PRODUCT', 'Registrieren Sie dieses Produkt unter');
