<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_INFO_SETTING')) define('_INFO_SETTING', '製品情報');
if (!defined('_INFO_SETTING_INSTRUCTION')) define('_INFO_SETTING_INSTRUCTION', '製品情報、バージョン、ライセンスを確認します。');
if (!defined('_INFO')) define('_INFO', '情報');
if (!defined('_LICENSE')) define('_LICENSE', 'ライセンス');
if (!defined('_LICENSE_UNAVAILABLE')) define('_LICENSE_UNAVAILABLE', 'ライセンスの内容を現在表示できません。');
if (!defined('_CREDIT')) define('_CREDIT', 'クレジット');
if (!defined('_VERSION')) define('_VERSION', 'バージョン');
if (!defined('_SERIAL')) define('_SERIAL', 'シリアル番号');
if (!defined('_LICENSED_TO')) define('_LICENSED_TO', 'ライセンス所有者');
if (!defined('_REGISTER_THIS_PRODUCT')) define('_REGISTER_THIS_PRODUCT', '製品の登録先：');
