<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_INFO_SETTING')) define('_INFO_SETTING', 'Informations sur le produit');
if (!defined('_INFO_SETTING_INSTRUCTION')) define('_INFO_SETTING_INSTRUCTION', 'Consultez les informations du produit, la version et la licence.');
if (!defined('_INFO')) define('_INFO', 'Informations');
if (!defined('_LICENSE')) define('_LICENSE', 'Licence');
if (!defined('_LICENSE_UNAVAILABLE')) define('_LICENSE_UNAVAILABLE', 'Le texte de la licence est indisponible.');
if (!defined('_CREDIT')) define('_CREDIT', 'Crédits');
if (!defined('_VERSION')) define('_VERSION', 'Version');
if (!defined('_SERIAL')) define('_SERIAL', 'Numéro de série');
if (!defined('_LICENSED_TO')) define('_LICENSED_TO', 'Licence accordée à');
if (!defined('_REGISTER_THIS_PRODUCT')) define('_REGISTER_THIS_PRODUCT', 'Enregistrez ce produit sur');
