<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_INFO_SETTING')) define('_INFO_SETTING', 'Información del producto');
if (!defined('_INFO_SETTING_INSTRUCTION')) define('_INFO_SETTING_INSTRUCTION', 'Consulta la información del producto, la versión y la licencia.');
if (!defined('_INFO')) define('_INFO', 'Información');
if (!defined('_LICENSE')) define('_LICENSE', 'Licencia');
if (!defined('_LICENSE_UNAVAILABLE')) define('_LICENSE_UNAVAILABLE', 'El texto de la licencia no está disponible.');
if (!defined('_CREDIT')) define('_CREDIT', 'Créditos');
if (!defined('_VERSION')) define('_VERSION', 'Versión');
if (!defined('_SERIAL')) define('_SERIAL', 'Número de serie');
if (!defined('_LICENSED_TO')) define('_LICENSED_TO', 'Licenciado a');
if (!defined('_REGISTER_THIS_PRODUCT')) define('_REGISTER_THIS_PRODUCT', 'Registra este producto en');
