<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_INFO_SETTING')) define('_INFO_SETTING', 'Informações do produto');
if (!defined('_INFO_SETTING_INSTRUCTION')) define('_INFO_SETTING_INSTRUCTION', 'Consulte informações do produto, versão e licença.');
if (!defined('_INFO')) define('_INFO', 'Informações');
if (!defined('_LICENSE')) define('_LICENSE', 'Licença');
if (!defined('_LICENSE_UNAVAILABLE')) define('_LICENSE_UNAVAILABLE', 'O texto da licença não está disponível.');
if (!defined('_CREDIT')) define('_CREDIT', 'Créditos');
if (!defined('_VERSION')) define('_VERSION', 'Versão');
if (!defined('_SERIAL')) define('_SERIAL', 'Número de série');
if (!defined('_LICENSED_TO')) define('_LICENSED_TO', 'Licenciado para');
if (!defined('_REGISTER_THIS_PRODUCT')) define('_REGISTER_THIS_PRODUCT', 'Registre este produto em');
