<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_JPOP_SETTING')) define('_JPOP_SETTING', 'Pop-ups');
if (!defined('_JPOP_NEW')) define('_JPOP_NEW', 'Novo');
if (!defined('_JPOP_BACK')) define('_JPOP_BACK', 'Voltar');
if (!defined('_JPOP_PAGE')) define('_JPOP_PAGE', 'Página');
if (!defined('_JPOP_LAST')) define('_JPOP_LAST', '&raquo;');
if (!defined('_JPOP_FIRST')) define('_JPOP_FIRST', '&laquo;');
if (!defined('_JPOP_PREV')) define('_JPOP_PREV', 'Anterior');
if (!defined('_JPOP_NEXT')) define('_JPOP_NEXT', 'Próximo');
if (!defined('_ACTIVED')) define('_ACTIVED', 'Ativar');
if (!defined('_DEACTIVED')) define('_DEACTIVED', 'Desativar');
if (!defined('_JPOP_NEW_SETTING')) define('_JPOP_NEW_SETTING', 'Novo pop-up');
if (!defined('_JPOP_TITLE')) define('_JPOP_TITLE', 'Título');
if (!defined('_JPOP_DES')) define('_JPOP_DES', 'Detalhes');
if (!defined('_JPOP_BG_TITLE')) define('_JPOP_BG_TITLE', 'Cor de fundo do título');
if (!defined('_JPOP_BG_DES')) define('_JPOP_BG_DES', 'Cor de fundo dos detalhes');
if (!defined('_JPOP_BG_BORDER')) define('_JPOP_BG_BORDER', 'Cor da borda');
if (!defined('_JPOP_EDIT_SETTING')) define('_JPOP_EDIT_SETTING', 'Editar pop-up');
