<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_JPOP_SETTING')) define('_JPOP_SETTING', 'Ventanas emergentes');
if (!defined('_JPOP_NEW')) define('_JPOP_NEW', 'Nuevo');
if (!defined('_JPOP_BACK')) define('_JPOP_BACK', 'Volver');
if (!defined('_JPOP_PAGE')) define('_JPOP_PAGE', 'Página');
if (!defined('_JPOP_LAST')) define('_JPOP_LAST', '&raquo;');
if (!defined('_JPOP_FIRST')) define('_JPOP_FIRST', '&laquo;');
if (!defined('_JPOP_PREV')) define('_JPOP_PREV', 'Anterior');
if (!defined('_JPOP_NEXT')) define('_JPOP_NEXT', 'Siguiente');
if (!defined('_ACTIVED')) define('_ACTIVED', 'Activar');
if (!defined('_DEACTIVED')) define('_DEACTIVED', 'Desactivar');
if (!defined('_JPOP_NEW_SETTING')) define('_JPOP_NEW_SETTING', 'Nueva ventana emergente');
if (!defined('_JPOP_TITLE')) define('_JPOP_TITLE', 'Título');
if (!defined('_JPOP_DES')) define('_JPOP_DES', 'Detalle');
if (!defined('_JPOP_BG_TITLE')) define('_JPOP_BG_TITLE', 'Color de fondo del título');
if (!defined('_JPOP_BG_DES')) define('_JPOP_BG_DES', 'Color de fondo del detalle');
if (!defined('_JPOP_BG_BORDER')) define('_JPOP_BG_BORDER', 'Color del borde');
if (!defined('_JPOP_EDIT_SETTING')) define('_JPOP_EDIT_SETTING', 'Editar ventana emergente');
