<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_JPOP_SETTING')) define('_JPOP_SETTING', 'ポップアップ設定');
if (!defined('_JPOP_NEW')) define('_JPOP_NEW', '新規');
if (!defined('_JPOP_BACK')) define('_JPOP_BACK', '戻る');
if (!defined('_JPOP_PAGE')) define('_JPOP_PAGE', 'ページ');
if (!defined('_JPOP_LAST')) define('_JPOP_LAST', '&raquo;');
if (!defined('_JPOP_FIRST')) define('_JPOP_FIRST', '&laquo;');
if (!defined('_JPOP_PREV')) define('_JPOP_PREV', '前へ');
if (!defined('_JPOP_NEXT')) define('_JPOP_NEXT', '次へ');
if (!defined('_ACTIVED')) define('_ACTIVED', '有効にする');
if (!defined('_DEACTIVED')) define('_DEACTIVED', '無効にする');
if (!defined('_JPOP_NEW_SETTING')) define('_JPOP_NEW_SETTING', 'ポップアップを追加');
if (!defined('_JPOP_TITLE')) define('_JPOP_TITLE', 'タイトル');
if (!defined('_JPOP_DES')) define('_JPOP_DES', '詳細');
if (!defined('_JPOP_BG_TITLE')) define('_JPOP_BG_TITLE', 'タイトルの背景色');
if (!defined('_JPOP_BG_DES')) define('_JPOP_BG_DES', '詳細の背景色');
if (!defined('_JPOP_BG_BORDER')) define('_JPOP_BG_BORDER', '枠線の色');
if (!defined('_JPOP_EDIT_SETTING')) define('_JPOP_EDIT_SETTING', 'ポップアップを編集');
