<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_JPOP_SETTING')) define('_JPOP_SETTING', 'Fenêtres contextuelles');
if (!defined('_JPOP_NEW')) define('_JPOP_NEW', 'Nouveau');
if (!defined('_JPOP_BACK')) define('_JPOP_BACK', 'Retour');
if (!defined('_JPOP_PAGE')) define('_JPOP_PAGE', 'Page');
if (!defined('_JPOP_LAST')) define('_JPOP_LAST', '&raquo;');
if (!defined('_JPOP_FIRST')) define('_JPOP_FIRST', '&laquo;');
if (!defined('_JPOP_PREV')) define('_JPOP_PREV', 'Précédent');
if (!defined('_JPOP_NEXT')) define('_JPOP_NEXT', 'Suivant');
if (!defined('_ACTIVED')) define('_ACTIVED', 'Activer');
if (!defined('_DEACTIVED')) define('_DEACTIVED', 'Désactiver');
if (!defined('_JPOP_NEW_SETTING')) define('_JPOP_NEW_SETTING', 'Nouvelle fenêtre contextuelle');
if (!defined('_JPOP_TITLE')) define('_JPOP_TITLE', 'Titre');
if (!defined('_JPOP_DES')) define('_JPOP_DES', 'Détails');
if (!defined('_JPOP_BG_TITLE')) define('_JPOP_BG_TITLE', 'Couleur de fond du titre');
if (!defined('_JPOP_BG_DES')) define('_JPOP_BG_DES', 'Couleur de fond des détails');
if (!defined('_JPOP_BG_BORDER')) define('_JPOP_BG_BORDER', 'Couleur de bordure');
if (!defined('_JPOP_EDIT_SETTING')) define('_JPOP_EDIT_SETTING', 'Modifier la fenêtre contextuelle');
