<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_JPOP_SETTING')) define('_JPOP_SETTING', 'Pop-ups');
if (!defined('_JPOP_NEW')) define('_JPOP_NEW', 'Neu');
if (!defined('_JPOP_BACK')) define('_JPOP_BACK', 'Zurück');
if (!defined('_JPOP_PAGE')) define('_JPOP_PAGE', 'Seite');
if (!defined('_JPOP_LAST')) define('_JPOP_LAST', '&raquo;');
if (!defined('_JPOP_FIRST')) define('_JPOP_FIRST', '&laquo;');
if (!defined('_JPOP_PREV')) define('_JPOP_PREV', 'Zurück');
if (!defined('_JPOP_NEXT')) define('_JPOP_NEXT', 'Weiter');
if (!defined('_ACTIVED')) define('_ACTIVED', 'Aktivieren');
if (!defined('_DEACTIVED')) define('_DEACTIVED', 'Deaktivieren');
if (!defined('_JPOP_NEW_SETTING')) define('_JPOP_NEW_SETTING', 'Neues Pop-up');
if (!defined('_JPOP_TITLE')) define('_JPOP_TITLE', 'Titel');
if (!defined('_JPOP_DES')) define('_JPOP_DES', 'Details');
if (!defined('_JPOP_BG_TITLE')) define('_JPOP_BG_TITLE', 'Hintergrundfarbe des Titels');
if (!defined('_JPOP_BG_DES')) define('_JPOP_BG_DES', 'Hintergrundfarbe der Details');
if (!defined('_JPOP_BG_BORDER')) define('_JPOP_BG_BORDER', 'Rahmenfarbe');
if (!defined('_JPOP_EDIT_SETTING')) define('_JPOP_EDIT_SETTING', 'Pop-up bearbeiten');
