<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_APITOKEN_SETTING')) define('_APITOKEN_SETTING', 'Tokens de API');
if (!defined('_APITOKEN_SETTING_INSTRUCTION')) define('_APITOKEN_SETTING_INSTRUCTION', 'Genera tokens Bearer para la API REST (api.php). Cada token usa la identidad y los permisos del usuario seleccionado.');
if (!defined('_APITOKEN_GENERATE')) define('_APITOKEN_GENERATE', 'Generar');
if (!defined('_APITOKEN_LABEL')) define('_APITOKEN_LABEL', 'Etiqueta (opcional)');
if (!defined('_APITOKEN_USER')) define('_APITOKEN_USER', 'Usuario');
if (!defined('_APITOKEN_CREATED')) define('_APITOKEN_CREATED', 'Creado');
if (!defined('_APITOKEN_LAST_USED')) define('_APITOKEN_LAST_USED', 'Último uso');
if (!defined('_APITOKEN_REVOKE')) define('_APITOKEN_REVOKE', 'Revocar');
if (!defined('_APITOKEN_NEW_TOKEN')) define('_APITOKEN_NEW_TOKEN', 'Token generado. Cópialo ahora; no volverá a mostrarse:');
if (!defined('_APITOKEN_COPY_NOW')) define('_APITOKEN_COPY_NOW', 'Úsalo así: Authorization: Bearer <token>');
