<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_APITOKEN_SETTING')) define('_APITOKEN_SETTING', 'APIトークン');
if (!defined('_APITOKEN_SETTING_INSTRUCTION')) define('_APITOKEN_SETTING_INSTRUCTION', 'REST API（api.php）用のBearerトークンを生成します。トークンは選択したユーザーの権限で動作します。');
if (!defined('_APITOKEN_GENERATE')) define('_APITOKEN_GENERATE', '生成');
if (!defined('_APITOKEN_LABEL')) define('_APITOKEN_LABEL', 'ラベル（任意）');
if (!defined('_APITOKEN_USER')) define('_APITOKEN_USER', 'ユーザー');
if (!defined('_APITOKEN_CREATED')) define('_APITOKEN_CREATED', '作成日時');
if (!defined('_APITOKEN_LAST_USED')) define('_APITOKEN_LAST_USED', '最終使用日時');
if (!defined('_APITOKEN_REVOKE')) define('_APITOKEN_REVOKE', '取り消す');
if (!defined('_APITOKEN_NEW_TOKEN')) define('_APITOKEN_NEW_TOKEN', 'トークンを生成しました。再表示されないため、今すぐコピーしてください：');
if (!defined('_APITOKEN_COPY_NOW')) define('_APITOKEN_COPY_NOW', '使用方法：Authorization: Bearer <token>');
