<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_APITOKEN_SETTING')) define('_APITOKEN_SETTING', 'Jetons API');
if (!defined('_APITOKEN_SETTING_INSTRUCTION')) define('_APITOKEN_SETTING_INSTRUCTION', 'Générez des jetons Bearer pour l’API REST (api.php). Chaque jeton utilise l’identité et les permissions de l’utilisateur choisi.');
if (!defined('_APITOKEN_GENERATE')) define('_APITOKEN_GENERATE', 'Générer');
if (!defined('_APITOKEN_LABEL')) define('_APITOKEN_LABEL', 'Libellé (facultatif)');
if (!defined('_APITOKEN_USER')) define('_APITOKEN_USER', 'Utilisateur');
if (!defined('_APITOKEN_CREATED')) define('_APITOKEN_CREATED', 'Créé');
if (!defined('_APITOKEN_LAST_USED')) define('_APITOKEN_LAST_USED', 'Dernière utilisation');
if (!defined('_APITOKEN_REVOKE')) define('_APITOKEN_REVOKE', 'Révoquer');
if (!defined('_APITOKEN_NEW_TOKEN')) define('_APITOKEN_NEW_TOKEN', 'Jeton généré. Copiez-le maintenant ; il ne sera plus affiché :');
if (!defined('_APITOKEN_COPY_NOW')) define('_APITOKEN_COPY_NOW', 'Utilisation : Authorization: Bearer <token>');
