<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_APITOKEN_SETTING')) define('_APITOKEN_SETTING', 'Tokens de API');
if (!defined('_APITOKEN_SETTING_INSTRUCTION')) define('_APITOKEN_SETTING_INSTRUCTION', 'Gere tokens Bearer para a API REST (api.php). Cada token usa a identidade e as permissões do usuário selecionado.');
if (!defined('_APITOKEN_GENERATE')) define('_APITOKEN_GENERATE', 'Gerar');
if (!defined('_APITOKEN_LABEL')) define('_APITOKEN_LABEL', 'Rótulo (opcional)');
if (!defined('_APITOKEN_USER')) define('_APITOKEN_USER', 'Usuário');
if (!defined('_APITOKEN_CREATED')) define('_APITOKEN_CREATED', 'Criado');
if (!defined('_APITOKEN_LAST_USED')) define('_APITOKEN_LAST_USED', 'Último uso');
if (!defined('_APITOKEN_REVOKE')) define('_APITOKEN_REVOKE', 'Revogar');
if (!defined('_APITOKEN_NEW_TOKEN')) define('_APITOKEN_NEW_TOKEN', 'Token gerado. Copie agora; ele não será exibido novamente:');
if (!defined('_APITOKEN_COPY_NOW')) define('_APITOKEN_COPY_NOW', 'Use assim: Authorization: Bearer <token>');
