<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_APITOKEN_SETTING')) define('_APITOKEN_SETTING', 'API-Token');
if (!defined('_APITOKEN_SETTING_INSTRUCTION')) define('_APITOKEN_SETTING_INSTRUCTION', 'Erstellen Sie Bearer-Token für die REST-API (api.php). Jedes Token verwendet die Identität und Rollenberechtigungen des ausgewählten Benutzers.');
if (!defined('_APITOKEN_GENERATE')) define('_APITOKEN_GENERATE', 'Erstellen');
if (!defined('_APITOKEN_LABEL')) define('_APITOKEN_LABEL', 'Bezeichnung (optional)');
if (!defined('_APITOKEN_USER')) define('_APITOKEN_USER', 'Benutzer');
if (!defined('_APITOKEN_CREATED')) define('_APITOKEN_CREATED', 'Erstellt');
if (!defined('_APITOKEN_LAST_USED')) define('_APITOKEN_LAST_USED', 'Zuletzt verwendet');
if (!defined('_APITOKEN_REVOKE')) define('_APITOKEN_REVOKE', 'Widerrufen');
if (!defined('_APITOKEN_NEW_TOKEN')) define('_APITOKEN_NEW_TOKEN', 'Token erstellt. Kopieren Sie es jetzt; es wird nicht erneut angezeigt:');
if (!defined('_APITOKEN_COPY_NOW')) define('_APITOKEN_COPY_NOW', 'Verwendung: Authorization: Bearer <token>');
