<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_CONTENT_SETTING')) define('_CONTENT_SETTING', 'コンテンツ設定');
if (!defined('_CONTENT_SETTING_INSTRUCTION')) define('_CONTENT_SETTING_INSTRUCTION', '新規を押してコンテンツを作成するか、戻るを押して設定に戻ります。');
if (!defined('_CONTENT_NEW_INSTRUCTION')) define('_CONTENT_NEW_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_CONTENT_EDIT_INSTRUCTION')) define('_CONTENT_EDIT_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_CONTENT_TITLE')) define('_CONTENT_TITLE', 'タイトル');
if (!defined('_CONTENT_MENU')) define('_CONTENT_MENU', 'メニューリンクを作成');
if (!defined('_CONTENT_NOT_FOUND')) define('_CONTENT_NOT_FOUND', 'コンテンツが見つかりません');
if (!defined('_CONTENT_NO_PERMISSION')) define('_CONTENT_NO_PERMISSION', 'この操作を行う権限がありません。');
if (!defined('_CONTENT_ALLOW_COMMENTS')) define('_CONTENT_ALLOW_COMMENTS', 'コメントを許可');
if (!defined('_CONTENT_COMMENTS')) define('_CONTENT_COMMENTS', 'コメント');
if (!defined('_CONTENT_POST_COMMENT')) define('_CONTENT_POST_COMMENT', 'コメントを投稿');
if (!defined('_CONTENT_COMMENT_REQUIRED')) define('_CONTENT_COMMENT_REQUIRED', 'コメントのすべての項目を入力してください。');
if (!defined('_CONTENT_CAPTCHA_INVALID')) define('_CONTENT_CAPTCHA_INVALID', '確認コードが正しくありません。');
if (!defined('_CONTENT_COMMENT_NAME')) define('_CONTENT_COMMENT_NAME', '名前');
if (!defined('_CONTENT_COMMENT_EMAIL')) define('_CONTENT_COMMENT_EMAIL', 'メールアドレス');
if (!defined('_CONTENT_COMMENT_VERIFY')) define('_CONTENT_COMMENT_VERIFY', '確認コード');
if (!defined('_CONTENT_COMMENT_FAILED')) define('_CONTENT_COMMENT_FAILED', 'コメントを保存できませんでした。戻ってもう一度お試しください。');
