<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_CONTENT_SETTING')) define('_CONTENT_SETTING', 'Gerenciamento de conteúdo');
if (!defined('_CONTENT_SETTING_INSTRUCTION')) define('_CONTENT_SETTING_INSTRUCTION', 'Clique em Novo para criar conteúdo ou em Voltar para retornar às configurações.');
if (!defined('_CONTENT_NEW_INSTRUCTION')) define('_CONTENT_NEW_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_CONTENT_EDIT_INSTRUCTION')) define('_CONTENT_EDIT_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_CONTENT_TITLE')) define('_CONTENT_TITLE', 'Título');
if (!defined('_CONTENT_MENU')) define('_CONTENT_MENU', 'Criar link no menu');
if (!defined('_CONTENT_NOT_FOUND')) define('_CONTENT_NOT_FOUND', 'Conteúdo não encontrado');
if (!defined('_CONTENT_NO_PERMISSION')) define('_CONTENT_NO_PERMISSION', 'Você não tem permissão para realizar esta ação.');
if (!defined('_CONTENT_ALLOW_COMMENTS')) define('_CONTENT_ALLOW_COMMENTS', 'Permitir comentários');
if (!defined('_CONTENT_COMMENTS')) define('_CONTENT_COMMENTS', 'Comentários');
if (!defined('_CONTENT_POST_COMMENT')) define('_CONTENT_POST_COMMENT', 'Publicar comentário');
if (!defined('_CONTENT_COMMENT_REQUIRED')) define('_CONTENT_COMMENT_REQUIRED', 'Preencha todos os campos do comentário.');
if (!defined('_CONTENT_CAPTCHA_INVALID')) define('_CONTENT_CAPTCHA_INVALID', 'O código de verificação está incorreto.');
if (!defined('_CONTENT_COMMENT_NAME')) define('_CONTENT_COMMENT_NAME', 'Nome');
if (!defined('_CONTENT_COMMENT_EMAIL')) define('_CONTENT_COMMENT_EMAIL', 'E-mail');
if (!defined('_CONTENT_COMMENT_VERIFY')) define('_CONTENT_COMMENT_VERIFY', 'Código de verificação');
if (!defined('_CONTENT_COMMENT_FAILED')) define('_CONTENT_COMMENT_FAILED', 'Não foi possível salvar seu comentário. Volte e tente novamente.');
