<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_CONTENT_SETTING')) define('_CONTENT_SETTING', 'Gestion du contenu');
if (!defined('_CONTENT_SETTING_INSTRUCTION')) define('_CONTENT_SETTING_INSTRUCTION', 'Cliquez sur Nouveau pour créer du contenu ou sur Retour pour revenir aux paramètres.');
if (!defined('_CONTENT_NEW_INSTRUCTION')) define('_CONTENT_NEW_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_CONTENT_EDIT_INSTRUCTION')) define('_CONTENT_EDIT_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_CONTENT_TITLE')) define('_CONTENT_TITLE', 'Titre');
if (!defined('_CONTENT_MENU')) define('_CONTENT_MENU', 'Créer un lien de menu');
if (!defined('_CONTENT_NOT_FOUND')) define('_CONTENT_NOT_FOUND', 'Contenu introuvable');
if (!defined('_CONTENT_NO_PERMISSION')) define('_CONTENT_NO_PERMISSION', 'Vous n’avez pas l’autorisation d’effectuer cette action.');
if (!defined('_CONTENT_ALLOW_COMMENTS')) define('_CONTENT_ALLOW_COMMENTS', 'Autoriser les commentaires');
if (!defined('_CONTENT_COMMENTS')) define('_CONTENT_COMMENTS', 'Commentaires');
if (!defined('_CONTENT_POST_COMMENT')) define('_CONTENT_POST_COMMENT', 'Publier le commentaire');
if (!defined('_CONTENT_COMMENT_REQUIRED')) define('_CONTENT_COMMENT_REQUIRED', 'Remplissez tous les champs du commentaire.');
if (!defined('_CONTENT_CAPTCHA_INVALID')) define('_CONTENT_CAPTCHA_INVALID', 'Le code de vérification est incorrect.');
if (!defined('_CONTENT_COMMENT_NAME')) define('_CONTENT_COMMENT_NAME', 'Nom');
if (!defined('_CONTENT_COMMENT_EMAIL')) define('_CONTENT_COMMENT_EMAIL', 'E-mail');
if (!defined('_CONTENT_COMMENT_VERIFY')) define('_CONTENT_COMMENT_VERIFY', 'Code de vérification');
if (!defined('_CONTENT_COMMENT_FAILED')) define('_CONTENT_COMMENT_FAILED', 'Impossible d’enregistrer votre commentaire. Revenez en arrière et réessayez.');
