<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_CONTENT_SETTING')) define('_CONTENT_SETTING', 'Inhaltsverwaltung');
if (!defined('_CONTENT_SETTING_INSTRUCTION')) define('_CONTENT_SETTING_INSTRUCTION', 'Klicken Sie auf Neu für einen Inhalt oder auf Zurück für die Einstellungen.');
if (!defined('_CONTENT_NEW_INSTRUCTION')) define('_CONTENT_NEW_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_CONTENT_EDIT_INSTRUCTION')) define('_CONTENT_EDIT_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_CONTENT_TITLE')) define('_CONTENT_TITLE', 'Titel');
if (!defined('_CONTENT_MENU')) define('_CONTENT_MENU', 'Menülink erstellen');
if (!defined('_CONTENT_NOT_FOUND')) define('_CONTENT_NOT_FOUND', 'Inhalt nicht gefunden');
if (!defined('_CONTENT_NO_PERMISSION')) define('_CONTENT_NO_PERMISSION', 'Sie haben keine Berechtigung für diese Aktion.');
if (!defined('_CONTENT_ALLOW_COMMENTS')) define('_CONTENT_ALLOW_COMMENTS', 'Kommentare erlauben');
if (!defined('_CONTENT_COMMENTS')) define('_CONTENT_COMMENTS', 'Kommentare');
if (!defined('_CONTENT_POST_COMMENT')) define('_CONTENT_POST_COMMENT', 'Kommentar senden');
if (!defined('_CONTENT_COMMENT_REQUIRED')) define('_CONTENT_COMMENT_REQUIRED', 'Bitte füllen Sie alle Kommentarfelder aus.');
if (!defined('_CONTENT_CAPTCHA_INVALID')) define('_CONTENT_CAPTCHA_INVALID', 'Der Bestätigungscode ist falsch.');
if (!defined('_CONTENT_COMMENT_NAME')) define('_CONTENT_COMMENT_NAME', 'Name');
if (!defined('_CONTENT_COMMENT_EMAIL')) define('_CONTENT_COMMENT_EMAIL', 'E-Mail');
if (!defined('_CONTENT_COMMENT_VERIFY')) define('_CONTENT_COMMENT_VERIFY', 'Bestätigungscode');
if (!defined('_CONTENT_COMMENT_FAILED')) define('_CONTENT_COMMENT_FAILED', 'Ihr Kommentar konnte nicht gespeichert werden. Gehen Sie zurück und versuchen Sie es erneut.');
