<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_CONTENT_SETTING')) define('_CONTENT_SETTING', 'Gestión de contenido');
if (!defined('_CONTENT_SETTING_INSTRUCTION')) define('_CONTENT_SETTING_INSTRUCTION', 'Pulsa Nuevo para crear contenido o Volver para regresar a la configuración.');
if (!defined('_CONTENT_NEW_INSTRUCTION')) define('_CONTENT_NEW_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_CONTENT_EDIT_INSTRUCTION')) define('_CONTENT_EDIT_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_CONTENT_TITLE')) define('_CONTENT_TITLE', 'Título');
if (!defined('_CONTENT_MENU')) define('_CONTENT_MENU', 'Crear enlace de menú');
if (!defined('_CONTENT_NOT_FOUND')) define('_CONTENT_NOT_FOUND', 'Contenido no encontrado');
if (!defined('_CONTENT_NO_PERMISSION')) define('_CONTENT_NO_PERMISSION', 'No tienes permiso para realizar esta acción.');
if (!defined('_CONTENT_ALLOW_COMMENTS')) define('_CONTENT_ALLOW_COMMENTS', 'Permitir comentarios');
if (!defined('_CONTENT_COMMENTS')) define('_CONTENT_COMMENTS', 'Comentarios');
if (!defined('_CONTENT_POST_COMMENT')) define('_CONTENT_POST_COMMENT', 'Publicar comentario');
if (!defined('_CONTENT_COMMENT_REQUIRED')) define('_CONTENT_COMMENT_REQUIRED', 'Completa todos los campos del comentario.');
if (!defined('_CONTENT_CAPTCHA_INVALID')) define('_CONTENT_CAPTCHA_INVALID', 'El código de verificación es incorrecto.');
if (!defined('_CONTENT_COMMENT_NAME')) define('_CONTENT_COMMENT_NAME', 'Nombre');
if (!defined('_CONTENT_COMMENT_EMAIL')) define('_CONTENT_COMMENT_EMAIL', 'Correo electrónico');
if (!defined('_CONTENT_COMMENT_VERIFY')) define('_CONTENT_COMMENT_VERIFY', 'Código de verificación');
if (!defined('_CONTENT_COMMENT_FAILED')) define('_CONTENT_COMMENT_FAILED', 'No se pudo guardar el comentario. Vuelve e inténtalo de nuevo.');
