<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_FILENAME')) define('_FILENAME', 'Nombre de archivo');
if (!defined('_FILESIZE')) define('_FILESIZE', 'Tamaño');
if (!defined('_FILETYPE')) define('_FILETYPE', 'Tipo');
if (!defined('_FILEPERMS')) define('_FILEPERMS', 'Permiso');
if (!defined('_EXPLORER_SETTING')) define('_EXPLORER_SETTING', 'Explorador de Lanai');
if (!defined('_EXPLORER_INSTRUCTION')) define('_EXPLORER_INSTRUCTION', 'Elige una opción para gestionar los archivos.');
if (!defined('_UPLOAD')) define('_UPLOAD', 'Subir');
if (!defined('_CANCEL')) define('_CANCEL', 'Volver');
if (!defined('_EXPLORER_UPLOAD_SETTING')) define('_EXPLORER_UPLOAD_SETTING', 'Subir');
if (!defined('_EXPLORER_UPLOAD_INSTRUCTION')) define('_EXPLORER_UPLOAD_INSTRUCTION', 'Selecciona los archivos y pulsa Guardar para subirlos.');
if (!defined('_FILE')) define('_FILE', 'Archivo');
