<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_FILENAME')) define('_FILENAME', 'Nome do arquivo');
if (!defined('_FILESIZE')) define('_FILESIZE', 'Tamanho');
if (!defined('_FILETYPE')) define('_FILETYPE', 'Tipo');
if (!defined('_FILEPERMS')) define('_FILEPERMS', 'Permissão');
if (!defined('_EXPLORER_SETTING')) define('_EXPLORER_SETTING', 'Explorador Lanai');
if (!defined('_EXPLORER_INSTRUCTION')) define('_EXPLORER_INSTRUCTION', 'Escolha uma opção para gerenciar seus arquivos.');
if (!defined('_UPLOAD')) define('_UPLOAD', 'Enviar');
if (!defined('_CANCEL')) define('_CANCEL', 'Voltar');
if (!defined('_EXPLORER_UPLOAD_SETTING')) define('_EXPLORER_UPLOAD_SETTING', 'Enviar');
if (!defined('_EXPLORER_UPLOAD_INSTRUCTION')) define('_EXPLORER_UPLOAD_INSTRUCTION', 'Selecione os arquivos e clique em Salvar para enviá-los.');
if (!defined('_FILE')) define('_FILE', 'Arquivo');
