<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_FILENAME')) define('_FILENAME', 'Nom du fichier');
if (!defined('_FILESIZE')) define('_FILESIZE', 'Taille');
if (!defined('_FILETYPE')) define('_FILETYPE', 'Type');
if (!defined('_FILEPERMS')) define('_FILEPERMS', 'Permission');
if (!defined('_EXPLORER_SETTING')) define('_EXPLORER_SETTING', 'Explorateur Lanai');
if (!defined('_EXPLORER_INSTRUCTION')) define('_EXPLORER_INSTRUCTION', 'Choisissez une option pour gérer vos fichiers.');
if (!defined('_UPLOAD')) define('_UPLOAD', 'Téléverser');
if (!defined('_CANCEL')) define('_CANCEL', 'Retour');
if (!defined('_EXPLORER_UPLOAD_SETTING')) define('_EXPLORER_UPLOAD_SETTING', 'Téléverser');
if (!defined('_EXPLORER_UPLOAD_INSTRUCTION')) define('_EXPLORER_UPLOAD_INSTRUCTION', 'Choisissez les fichiers puis cliquez sur Enregistrer pour les téléverser.');
if (!defined('_FILE')) define('_FILE', 'Fichier');
