<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_FILENAME')) define('_FILENAME', 'Dateiname');
if (!defined('_FILESIZE')) define('_FILESIZE', 'Größe');
if (!defined('_FILETYPE')) define('_FILETYPE', 'Typ');
if (!defined('_FILEPERMS')) define('_FILEPERMS', 'Berechtigung');
if (!defined('_EXPLORER_SETTING')) define('_EXPLORER_SETTING', 'Lanai-Dateimanager');
if (!defined('_EXPLORER_INSTRUCTION')) define('_EXPLORER_INSTRUCTION', 'Wählen Sie eine Option zur Dateiverwaltung.');
if (!defined('_UPLOAD')) define('_UPLOAD', 'Hochladen');
if (!defined('_CANCEL')) define('_CANCEL', 'Zurück');
if (!defined('_EXPLORER_UPLOAD_SETTING')) define('_EXPLORER_UPLOAD_SETTING', 'Hochladen');
if (!defined('_EXPLORER_UPLOAD_INSTRUCTION')) define('_EXPLORER_UPLOAD_INSTRUCTION', 'Wählen Sie Dateien und klicken Sie zum Hochladen auf Speichern.');
if (!defined('_FILE')) define('_FILE', 'Datei');
