<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_FILENAME')) define('_FILENAME', 'ファイル名');
if (!defined('_FILESIZE')) define('_FILESIZE', 'サイズ');
if (!defined('_FILETYPE')) define('_FILETYPE', '種類');
if (!defined('_FILEPERMS')) define('_FILEPERMS', '権限');
if (!defined('_EXPLORER_SETTING')) define('_EXPLORER_SETTING', 'Lanaiファイル管理');
if (!defined('_EXPLORER_INSTRUCTION')) define('_EXPLORER_INSTRUCTION', 'ファイルを管理するメニューを選択してください。');
if (!defined('_UPLOAD')) define('_UPLOAD', 'アップロード');
if (!defined('_CANCEL')) define('_CANCEL', '戻る');
if (!defined('_EXPLORER_UPLOAD_SETTING')) define('_EXPLORER_UPLOAD_SETTING', 'アップロード');
if (!defined('_EXPLORER_UPLOAD_INSTRUCTION')) define('_EXPLORER_UPLOAD_INSTRUCTION', 'ファイルを選択し、保存を押してアップロードしてください。');
if (!defined('_FILE')) define('_FILE', 'ファイル');
