<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SEARCH_LANAI')) define('_SEARCH_LANAI', 'Suchen');
if (!defined('_SEARCH_LANAI_INSTRUCTION')) define('_SEARCH_LANAI_INSTRUCTION', 'Geben Sie ein Schlüsselwort ein und wählen Sie den Suchbereich.');
if (!defined('_SEARCH_KEYWORD')) define('_SEARCH_KEYWORD', 'Schlüsselwort');
if (!defined('_SEARCH_ITEM')) define('_SEARCH_ITEM', 'Suchen in');
if (!defined('_SEARCH_WORD')) define('_SEARCH_WORD', 'Wort');
if (!defined('_SEARCH_PHASE')) define('_SEARCH_PHASE', 'Wortgruppe');
if (!defined('_SEARCH')) define('_SEARCH', 'Suchen');
if (!defined('_FOUND')) define('_FOUND', 'gefunden');
if (!defined('_ITEMS')) define('_ITEMS', 'Einträge');
