<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SEARCH_LANAI')) define('_SEARCH_LANAI', '検索');
if (!defined('_SEARCH_LANAI_INSTRUCTION')) define('_SEARCH_LANAI_INSTRUCTION', 'キーワードと検索対象を指定してください。');
if (!defined('_SEARCH_KEYWORD')) define('_SEARCH_KEYWORD', 'キーワード');
if (!defined('_SEARCH_ITEM')) define('_SEARCH_ITEM', '検索対象');
if (!defined('_SEARCH_WORD')) define('_SEARCH_WORD', '単語');
if (!defined('_SEARCH_PHASE')) define('_SEARCH_PHASE', 'フレーズ');
if (!defined('_SEARCH')) define('_SEARCH', '検索');
if (!defined('_FOUND')) define('_FOUND', '件見つかりました');
if (!defined('_ITEMS')) define('_ITEMS', '項目');
