<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SEARCH_LANAI')) define('_SEARCH_LANAI', 'Rechercher');
if (!defined('_SEARCH_LANAI_INSTRUCTION')) define('_SEARCH_LANAI_INSTRUCTION', 'Saisissez un mot-clé et choisissez où rechercher.');
if (!defined('_SEARCH_KEYWORD')) define('_SEARCH_KEYWORD', 'Mot-clé');
if (!defined('_SEARCH_ITEM')) define('_SEARCH_ITEM', 'Rechercher dans');
if (!defined('_SEARCH_WORD')) define('_SEARCH_WORD', 'Mot');
if (!defined('_SEARCH_PHASE')) define('_SEARCH_PHASE', 'Expression');
if (!defined('_SEARCH')) define('_SEARCH', 'Rechercher');
if (!defined('_FOUND')) define('_FOUND', 'trouvés');
if (!defined('_ITEMS')) define('_ITEMS', 'éléments');
