<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SEARCH_LANAI')) define('_SEARCH_LANAI', 'Pesquisar');
if (!defined('_SEARCH_LANAI_INSTRUCTION')) define('_SEARCH_LANAI_INSTRUCTION', 'Digite uma palavra-chave e escolha onde pesquisar.');
if (!defined('_SEARCH_KEYWORD')) define('_SEARCH_KEYWORD', 'Palavra-chave');
if (!defined('_SEARCH_ITEM')) define('_SEARCH_ITEM', 'Pesquisar em');
if (!defined('_SEARCH_WORD')) define('_SEARCH_WORD', 'Palavra');
if (!defined('_SEARCH_PHASE')) define('_SEARCH_PHASE', 'Frase');
if (!defined('_SEARCH')) define('_SEARCH', 'Pesquisar');
if (!defined('_FOUND')) define('_FOUND', 'encontrados');
if (!defined('_ITEMS')) define('_ITEMS', 'itens');
