<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SEARCH_LANAI')) define('_SEARCH_LANAI', 'Buscar');
if (!defined('_SEARCH_LANAI_INSTRUCTION')) define('_SEARCH_LANAI_INSTRUCTION', 'Introduce una palabra clave y elige dónde buscar.');
if (!defined('_SEARCH_KEYWORD')) define('_SEARCH_KEYWORD', 'Palabra clave');
if (!defined('_SEARCH_ITEM')) define('_SEARCH_ITEM', 'Buscar en');
if (!defined('_SEARCH_WORD')) define('_SEARCH_WORD', 'Palabra');
if (!defined('_SEARCH_PHASE')) define('_SEARCH_PHASE', 'Frase');
if (!defined('_SEARCH')) define('_SEARCH', 'Buscar');
if (!defined('_FOUND')) define('_FOUND', 'resultados');
if (!defined('_ITEMS')) define('_ITEMS', 'elementos');
