<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_MODULE_SETTING')) define('_MODULE_SETTING', 'モジュール設定');
if (!defined('_MODULE_SETTING_INSTRUCTION')) define('_MODULE_SETTING_INSTRUCTION', '新規を押してモジュールをインストールするか、戻るを押して設定に戻ります。');
if (!defined('_MODULE_TITLE')) define('_MODULE_TITLE', 'モジュールのタイトル');
if (!defined('_MODULE_NAME')) define('_MODULE_NAME', 'モジュール名');
if (!defined('_MODULE_NEW')) define('_MODULE_NEW', 'モジュール設定');
if (!defined('_MODULE_NEW_INSTRUCTION')) define('_MODULE_NEW_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_MODULE_ZIPFILE_UPLOAD')) define('_MODULE_ZIPFILE_UPLOAD', 'モジュールのZIPファイルをアップロード');
if (!defined('_MODULE_ZIPFILE_REMOTE')) define('_MODULE_ZIPFILE_REMOTE', 'リモートモジュールのZIPを展開');
if (!defined('_MODULE_ACTIVE')) define('_MODULE_ACTIVE', '有効');
if (!defined('_MODULE_EDIT')) define('_MODULE_EDIT', 'モジュール設定');
if (!defined('_MODULE_EDIT_INSTRUCTION')) define('_MODULE_EDIT_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_MODULE_DIR_REMOTE')) define('_MODULE_DIR_REMOTE', '既存モジュールのディレクトリ');
