<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_MODULE_SETTING')) define('_MODULE_SETTING', 'Module');
if (!defined('_MODULE_SETTING_INSTRUCTION')) define('_MODULE_SETTING_INSTRUCTION', 'Klicken Sie auf Neu zum Installieren eines Moduls oder auf Zurück für die Einstellungen.');
if (!defined('_MODULE_TITLE')) define('_MODULE_TITLE', 'Modultitel');
if (!defined('_MODULE_NAME')) define('_MODULE_NAME', 'Modulname');
if (!defined('_MODULE_NEW')) define('_MODULE_NEW', 'Module');
if (!defined('_MODULE_NEW_INSTRUCTION')) define('_MODULE_NEW_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_MODULE_ZIPFILE_UPLOAD')) define('_MODULE_ZIPFILE_UPLOAD', 'Modul-ZIP hochladen');
if (!defined('_MODULE_ZIPFILE_REMOTE')) define('_MODULE_ZIPFILE_REMOTE', 'Entfernte Modul-ZIP entpacken');
if (!defined('_MODULE_ACTIVE')) define('_MODULE_ACTIVE', 'Aktiv');
if (!defined('_MODULE_EDIT')) define('_MODULE_EDIT', 'Module');
if (!defined('_MODULE_EDIT_INSTRUCTION')) define('_MODULE_EDIT_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_MODULE_DIR_REMOTE')) define('_MODULE_DIR_REMOTE', 'Vorhandenes Modulverzeichnis');
