<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_MODULE_SETTING')) define('_MODULE_SETTING', 'Módulos');
if (!defined('_MODULE_SETTING_INSTRUCTION')) define('_MODULE_SETTING_INSTRUCTION', 'Clique em Novo para instalar um módulo ou em Voltar para retornar às configurações.');
if (!defined('_MODULE_TITLE')) define('_MODULE_TITLE', 'Título do módulo');
if (!defined('_MODULE_NAME')) define('_MODULE_NAME', 'Nome do módulo');
if (!defined('_MODULE_NEW')) define('_MODULE_NEW', 'Módulos');
if (!defined('_MODULE_NEW_INSTRUCTION')) define('_MODULE_NEW_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_MODULE_ZIPFILE_UPLOAD')) define('_MODULE_ZIPFILE_UPLOAD', 'Enviar ZIP do módulo');
if (!defined('_MODULE_ZIPFILE_REMOTE')) define('_MODULE_ZIPFILE_REMOTE', 'Extrair ZIP remoto do módulo');
if (!defined('_MODULE_ACTIVE')) define('_MODULE_ACTIVE', 'Ativo');
if (!defined('_MODULE_EDIT')) define('_MODULE_EDIT', 'Módulos');
if (!defined('_MODULE_EDIT_INSTRUCTION')) define('_MODULE_EDIT_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_MODULE_DIR_REMOTE')) define('_MODULE_DIR_REMOTE', 'Diretório do módulo existente');
