<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_MODULE_SETTING')) define('_MODULE_SETTING', 'Módulos');
if (!defined('_MODULE_SETTING_INSTRUCTION')) define('_MODULE_SETTING_INSTRUCTION', 'Pulsa Nuevo para instalar un módulo o Volver para regresar a la configuración.');
if (!defined('_MODULE_TITLE')) define('_MODULE_TITLE', 'Título del módulo');
if (!defined('_MODULE_NAME')) define('_MODULE_NAME', 'Nombre del módulo');
if (!defined('_MODULE_NEW')) define('_MODULE_NEW', 'Módulos');
if (!defined('_MODULE_NEW_INSTRUCTION')) define('_MODULE_NEW_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_MODULE_ZIPFILE_UPLOAD')) define('_MODULE_ZIPFILE_UPLOAD', 'Subir archivo ZIP del módulo');
if (!defined('_MODULE_ZIPFILE_REMOTE')) define('_MODULE_ZIPFILE_REMOTE', 'Extraer ZIP remoto del módulo');
if (!defined('_MODULE_ACTIVE')) define('_MODULE_ACTIVE', 'Activo');
if (!defined('_MODULE_EDIT')) define('_MODULE_EDIT', 'Módulos');
if (!defined('_MODULE_EDIT_INSTRUCTION')) define('_MODULE_EDIT_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_MODULE_DIR_REMOTE')) define('_MODULE_DIR_REMOTE', 'Directorio del módulo existente');
