<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_MODULE_SETTING')) define('_MODULE_SETTING', 'Modules');
if (!defined('_MODULE_SETTING_INSTRUCTION')) define('_MODULE_SETTING_INSTRUCTION', 'Cliquez sur Nouveau pour installer un module ou sur Retour pour revenir aux paramètres.');
if (!defined('_MODULE_TITLE')) define('_MODULE_TITLE', 'Titre du module');
if (!defined('_MODULE_NAME')) define('_MODULE_NAME', 'Nom du module');
if (!defined('_MODULE_NEW')) define('_MODULE_NEW', 'Modules');
if (!defined('_MODULE_NEW_INSTRUCTION')) define('_MODULE_NEW_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_MODULE_ZIPFILE_UPLOAD')) define('_MODULE_ZIPFILE_UPLOAD', 'Téléverser le ZIP du module');
if (!defined('_MODULE_ZIPFILE_REMOTE')) define('_MODULE_ZIPFILE_REMOTE', 'Extraire le ZIP distant du module');
if (!defined('_MODULE_ACTIVE')) define('_MODULE_ACTIVE', 'Actif');
if (!defined('_MODULE_EDIT')) define('_MODULE_EDIT', 'Modules');
if (!defined('_MODULE_EDIT_INSTRUCTION')) define('_MODULE_EDIT_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_MODULE_DIR_REMOTE')) define('_MODULE_DIR_REMOTE', 'Dossier du module existant');
