<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_BACKUP_SETTING')) define('_BACKUP_SETTING', 'Copias de seguridad');
if (!defined('_BACKUP_INSTRUCTION')) define('_BACKUP_INSTRUCTION', 'Pulsa Nuevo para crear una copia de seguridad o Volver para regresar a la configuración.');
if (!defined('_FILENAME')) define('_FILENAME', 'Nombre de archivo');
if (!defined('_SIZE')) define('_SIZE', 'Tamaño');
if (!defined('_MODIFIED')) define('_MODIFIED', 'Modificado');
if (!defined('_DOWNLOAD')) define('_DOWNLOAD', 'Descargar');
if (!defined('_RESTORE')) define('_RESTORE', 'Restaurar');
if (!defined('_BACKUP_CHOOSE_TABLE_SETTING')) define('_BACKUP_CHOOSE_TABLE_SETTING', 'Selecciona las tablas para la copia de seguridad.');
if (!defined('_BACKUP_CHOOSE_TABLE_INSTRUCTION')) define('_BACKUP_CHOOSE_TABLE_INSTRUCTION', 'Pulsa Guardar para crear la copia de las tablas o Volver para regresar a la configuración.');
if (!defined('_BACKUP_SCHEMA')) define('_BACKUP_SCHEMA', 'Respaldar estructura');
if (!defined('_BACKUP_VALUE')) define('_BACKUP_VALUE', 'Respaldar datos');
if (!defined('_RESTORE_QUESTION')) define('_RESTORE_QUESTION', '¿Quieres restaurar los datos?');
if (!defined('_EXECUTE')) define('_EXECUTE', 'Ejecutar');
if (!defined('_ROWS')) define('_ROWS', 'filas');
if (!defined('_ERROR')) define('_ERROR', 'No se pudo ejecutar');
if (!defined('_BACKUP_COMPLETE')) define('_BACKUP_COMPLETE', 'Copia de seguridad completada');
