<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_BACKUP_SETTING')) define('_BACKUP_SETTING', 'Sicherungen');
if (!defined('_BACKUP_INSTRUCTION')) define('_BACKUP_INSTRUCTION', 'Klicken Sie auf Neu für eine Sicherung oder auf Zurück für die Einstellungen.');
if (!defined('_FILENAME')) define('_FILENAME', 'Dateiname');
if (!defined('_SIZE')) define('_SIZE', 'Größe');
if (!defined('_MODIFIED')) define('_MODIFIED', 'Geändert');
if (!defined('_DOWNLOAD')) define('_DOWNLOAD', 'Herunterladen');
if (!defined('_RESTORE')) define('_RESTORE', 'Wiederherstellen');
if (!defined('_BACKUP_CHOOSE_TABLE_SETTING')) define('_BACKUP_CHOOSE_TABLE_SETTING', 'Wählen Sie die zu sichernden Tabellen.');
if (!defined('_BACKUP_CHOOSE_TABLE_INSTRUCTION')) define('_BACKUP_CHOOSE_TABLE_INSTRUCTION', 'Klicken Sie auf Speichern für eine Tabellensicherung oder auf Zurück für die Einstellungen.');
if (!defined('_BACKUP_SCHEMA')) define('_BACKUP_SCHEMA', 'Struktur sichern');
if (!defined('_BACKUP_VALUE')) define('_BACKUP_VALUE', 'Daten sichern');
if (!defined('_RESTORE_QUESTION')) define('_RESTORE_QUESTION', 'Möchten Sie Ihre Daten wiederherstellen?');
if (!defined('_EXECUTE')) define('_EXECUTE', 'Ausführen');
if (!defined('_ROWS')) define('_ROWS', 'Zeilen');
if (!defined('_ERROR')) define('_ERROR', 'Ausführung fehlgeschlagen');
if (!defined('_BACKUP_COMPLETE')) define('_BACKUP_COMPLETE', 'Sicherung abgeschlossen');
