<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_BACKUP_SETTING')) define('_BACKUP_SETTING', 'Backups');
if (!defined('_BACKUP_INSTRUCTION')) define('_BACKUP_INSTRUCTION', 'Clique em Novo para criar um backup ou em Voltar para retornar às configurações.');
if (!defined('_FILENAME')) define('_FILENAME', 'Nome do arquivo');
if (!defined('_SIZE')) define('_SIZE', 'Tamanho');
if (!defined('_MODIFIED')) define('_MODIFIED', 'Modificado');
if (!defined('_DOWNLOAD')) define('_DOWNLOAD', 'Baixar');
if (!defined('_RESTORE')) define('_RESTORE', 'Restaurar');
if (!defined('_BACKUP_CHOOSE_TABLE_SETTING')) define('_BACKUP_CHOOSE_TABLE_SETTING', 'Selecione as tabelas para o backup.');
if (!defined('_BACKUP_CHOOSE_TABLE_INSTRUCTION')) define('_BACKUP_CHOOSE_TABLE_INSTRUCTION', 'Clique em Salvar para criar o backup das tabelas ou em Voltar para retornar às configurações.');
if (!defined('_BACKUP_SCHEMA')) define('_BACKUP_SCHEMA', 'Salvar estrutura');
if (!defined('_BACKUP_VALUE')) define('_BACKUP_VALUE', 'Salvar dados');
if (!defined('_RESTORE_QUESTION')) define('_RESTORE_QUESTION', 'Deseja restaurar seus dados?');
if (!defined('_EXECUTE')) define('_EXECUTE', 'Executar');
if (!defined('_ROWS')) define('_ROWS', 'linhas');
if (!defined('_ERROR')) define('_ERROR', 'Não foi possível executar');
if (!defined('_BACKUP_COMPLETE')) define('_BACKUP_COMPLETE', 'Backup concluído');
