<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_BACKUP_SETTING')) define('_BACKUP_SETTING', 'バックアップ設定');
if (!defined('_BACKUP_INSTRUCTION')) define('_BACKUP_INSTRUCTION', '新規を押してバックアップを作成するか、戻るを押して設定に戻ります。');
if (!defined('_FILENAME')) define('_FILENAME', 'ファイル名');
if (!defined('_SIZE')) define('_SIZE', 'サイズ');
if (!defined('_MODIFIED')) define('_MODIFIED', '更新日時');
if (!defined('_DOWNLOAD')) define('_DOWNLOAD', 'ダウンロード');
if (!defined('_RESTORE')) define('_RESTORE', '復元');
if (!defined('_BACKUP_CHOOSE_TABLE_SETTING')) define('_BACKUP_CHOOSE_TABLE_SETTING', 'バックアップするテーブルを選択してください。');
if (!defined('_BACKUP_CHOOSE_TABLE_INSTRUCTION')) define('_BACKUP_CHOOSE_TABLE_INSTRUCTION', '保存を押してテーブルをバックアップするか、戻るを押して設定に戻ります。');
if (!defined('_BACKUP_SCHEMA')) define('_BACKUP_SCHEMA', '構造をバックアップ');
if (!defined('_BACKUP_VALUE')) define('_BACKUP_VALUE', 'データをバックアップ');
if (!defined('_RESTORE_QUESTION')) define('_RESTORE_QUESTION', 'データを復元しますか？');
if (!defined('_EXECUTE')) define('_EXECUTE', '実行');
if (!defined('_ROWS')) define('_ROWS', '行');
if (!defined('_ERROR')) define('_ERROR', '実行できません');
if (!defined('_BACKUP_COMPLETE')) define('_BACKUP_COMPLETE', 'バックアップ完了');
