<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_BACKUP_SETTING')) define('_BACKUP_SETTING', 'Sauvegardes');
if (!defined('_BACKUP_INSTRUCTION')) define('_BACKUP_INSTRUCTION', 'Cliquez sur Nouveau pour créer une sauvegarde ou sur Retour pour revenir aux paramètres.');
if (!defined('_FILENAME')) define('_FILENAME', 'Nom du fichier');
if (!defined('_SIZE')) define('_SIZE', 'Taille');
if (!defined('_MODIFIED')) define('_MODIFIED', 'Modifié');
if (!defined('_DOWNLOAD')) define('_DOWNLOAD', 'Télécharger');
if (!defined('_RESTORE')) define('_RESTORE', 'Restaurer');
if (!defined('_BACKUP_CHOOSE_TABLE_SETTING')) define('_BACKUP_CHOOSE_TABLE_SETTING', 'Choisissez les tables à sauvegarder.');
if (!defined('_BACKUP_CHOOSE_TABLE_INSTRUCTION')) define('_BACKUP_CHOOSE_TABLE_INSTRUCTION', 'Cliquez sur Enregistrer pour sauvegarder les tables ou sur Retour pour revenir aux paramètres.');
if (!defined('_BACKUP_SCHEMA')) define('_BACKUP_SCHEMA', 'Sauvegarder la structure');
if (!defined('_BACKUP_VALUE')) define('_BACKUP_VALUE', 'Sauvegarder les données');
if (!defined('_RESTORE_QUESTION')) define('_RESTORE_QUESTION', 'Voulez-vous restaurer vos données ?');
if (!defined('_EXECUTE')) define('_EXECUTE', 'Exécuter');
if (!defined('_ROWS')) define('_ROWS', 'lignes');
if (!defined('_ERROR')) define('_ERROR', 'Impossible d’exécuter');
if (!defined('_BACKUP_COMPLETE')) define('_BACKUP_COMPLETE', 'Sauvegarde terminée');
