<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_SITE_MAP')) define('_SITE_MAP', 'サイトマップ');
if (!defined('_SITE_MAP_GOOGLE_LINK')) define('_SITE_MAP_GOOGLE_LINK', '以下の画像リンクをGoogleサイトマップに追加してください。');
