<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_SITE_MAP')) define('_SITE_MAP', 'Sitemap');
if (!defined('_SITE_MAP_GOOGLE_LINK')) define('_SITE_MAP_GOOGLE_LINK', 'Verwenden Sie den folgenden Bildlink für Ihre Google-Sitemap.');
