<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_SITE_MAP')) define('_SITE_MAP', 'Mapa do site');
if (!defined('_SITE_MAP_GOOGLE_LINK')) define('_SITE_MAP_GOOGLE_LINK', 'Use o link da imagem abaixo para adicionar ao mapa do site do Google.');
