<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_SITE_MAP')) define('_SITE_MAP', 'Plan du site');
if (!defined('_SITE_MAP_GOOGLE_LINK')) define('_SITE_MAP_GOOGLE_LINK', 'Utilisez le lien d’image suivant pour votre plan de site Google.');
