<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_CFG_SETTING')) define('_CFG_SETTING', 'Configuración y metadatos');
if (!defined('_CFG_OFFLINE')) define('_CFG_OFFLINE', 'Sitio fuera de línea');
if (!defined('_CFG_KEYWORDS')) define('_CFG_KEYWORDS', 'Palabra clave');
if (!defined('_CFG_DESCRIPTION')) define('_CFG_DESCRIPTION', 'Descripción');
if (!defined('_CFG_ABSTRACT')) define('_CFG_ABSTRACT', 'Resumen');
if (!defined('_CFG_AUTHOR')) define('_CFG_AUTHOR', 'Autor');
if (!defined('_CFG_DISTRIBUTION')) define('_CFG_DISTRIBUTION', 'Distribución');
if (!defined('_CFG_COPY')) define('_CFG_COPY', 'Derechos de autor');
if (!defined('_CFG_CANNOT_WRITE')) define('_CFG_CANNOT_WRITE', 'No se puede escribir la configuración. Revisa los permisos del archivo.');
