<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_CFG_SETTING')) define('_CFG_SETTING', '設定とメタデータ');
if (!defined('_CFG_OFFLINE')) define('_CFG_OFFLINE', 'サイトをオフラインにする');
if (!defined('_CFG_KEYWORDS')) define('_CFG_KEYWORDS', 'キーワード');
if (!defined('_CFG_DESCRIPTION')) define('_CFG_DESCRIPTION', '説明');
if (!defined('_CFG_ABSTRACT')) define('_CFG_ABSTRACT', '概要');
if (!defined('_CFG_AUTHOR')) define('_CFG_AUTHOR', '作成者');
if (!defined('_CFG_DISTRIBUTION')) define('_CFG_DISTRIBUTION', '配信範囲');
if (!defined('_CFG_COPY')) define('_CFG_COPY', '著作権');
if (!defined('_CFG_CANNOT_WRITE')) define('_CFG_CANNOT_WRITE', '設定ファイルに書き込めません。ファイルの権限を確認してください。');
