<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_CFG_SETTING')) define('_CFG_SETTING', 'Configuration et métadonnées');
if (!defined('_CFG_OFFLINE')) define('_CFG_OFFLINE', 'Site hors ligne');
if (!defined('_CFG_KEYWORDS')) define('_CFG_KEYWORDS', 'Mot-clé');
if (!defined('_CFG_DESCRIPTION')) define('_CFG_DESCRIPTION', 'Description');
if (!defined('_CFG_ABSTRACT')) define('_CFG_ABSTRACT', 'Résumé');
if (!defined('_CFG_AUTHOR')) define('_CFG_AUTHOR', 'Auteur');
if (!defined('_CFG_DISTRIBUTION')) define('_CFG_DISTRIBUTION', 'Diffusion');
if (!defined('_CFG_COPY')) define('_CFG_COPY', 'Droits d’auteur');
if (!defined('_CFG_CANNOT_WRITE')) define('_CFG_CANNOT_WRITE', 'Impossible d’écrire la configuration. Vérifiez les permissions du fichier.');
