<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_CFG_SETTING')) define('_CFG_SETTING', 'Konfiguration und Metadaten');
if (!defined('_CFG_OFFLINE')) define('_CFG_OFFLINE', 'Website offline');
if (!defined('_CFG_KEYWORDS')) define('_CFG_KEYWORDS', 'Schlüsselwort');
if (!defined('_CFG_DESCRIPTION')) define('_CFG_DESCRIPTION', 'Beschreibung');
if (!defined('_CFG_ABSTRACT')) define('_CFG_ABSTRACT', 'Zusammenfassung');
if (!defined('_CFG_AUTHOR')) define('_CFG_AUTHOR', 'Autor');
if (!defined('_CFG_DISTRIBUTION')) define('_CFG_DISTRIBUTION', 'Verbreitung');
if (!defined('_CFG_COPY')) define('_CFG_COPY', 'Urheberrecht');
if (!defined('_CFG_CANNOT_WRITE')) define('_CFG_CANNOT_WRITE', 'Konfigurationsdatei nicht beschreibbar. Prüfen Sie die Dateiberechtigungen.');
