<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_CFG_SETTING')) define('_CFG_SETTING', 'Configuração e metadados');
if (!defined('_CFG_OFFLINE')) define('_CFG_OFFLINE', 'Site fora do ar');
if (!defined('_CFG_KEYWORDS')) define('_CFG_KEYWORDS', 'Palavra-chave');
if (!defined('_CFG_DESCRIPTION')) define('_CFG_DESCRIPTION', 'Descrição');
if (!defined('_CFG_ABSTRACT')) define('_CFG_ABSTRACT', 'Resumo');
if (!defined('_CFG_AUTHOR')) define('_CFG_AUTHOR', 'Autor');
if (!defined('_CFG_DISTRIBUTION')) define('_CFG_DISTRIBUTION', 'Distribuição');
if (!defined('_CFG_COPY')) define('_CFG_COPY', 'Direitos autorais');
if (!defined('_CFG_CANNOT_WRITE')) define('_CFG_CANNOT_WRITE', 'Não é possível gravar a configuração. Verifique as permissões do arquivo.');
