<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_SETTING')) define('_SETTING', 'Gestionar');
if (!defined('_SITE_SETTING')) define('_SITE_SETTING', 'Configuración del sitio');
