// Evaluate in the isolated tests/router.php page, never on a real installation.
(async () => {
    if (location.hostname !== '127.0.0.1' || document.title !== 'Explorer test') throw new Error('Use the isolated Explorer test page.');
    const passes = [], errors = [];
    window.addEventListener('error', event => errors.push(event.message));
    const get = id => document.getElementById('explorer-' + id);
    const wait = async (predicate, label) => { for (let n = 0; n < 150; n++) { if (predicate()) return; await new Promise(resolve => setTimeout(resolve, 50)); } throw new Error(label + ': ' + get('status').textContent); };
    const check = (ok, label) => { if (!ok) throw new Error(label); passes.push(label); };
    const rows = () => [...document.querySelectorAll('#explorer-rows tr')];
    const choose = name => { const row = rows().find(row => row.querySelector('.file-name')?.textContent === name); if (!row) throw new Error('Missing row: ' + name); const input = row.querySelector('input'); input.checked = true; input.dispatchEvent(new Event('change')); return row; };
    const action = name => document.querySelector('[data-action="' + name + '"]').click();
    await wait(() => get('status').textContent.includes('item(s)'), 'Initial listing');
    const transfer = new DataTransfer(); transfer.items.add(new File(['alpha content'], 'alpha.txt', { type: 'text/plain' })); transfer.items.add(new File(['beta content'], 'beta.txt', { type: 'text/plain' }));
    get('upload').files = transfer.files; get('upload').dispatchEvent(new Event('change'));
    await wait(() => !get('upload').disabled && get('status').textContent === '2 of 2 files uploaded.', 'Batch upload');
    check(rows().length === 2, 'Multiple uploads appear as compact rows');
    get('select-all').click(); check(get('selection').textContent === '2 selected', 'Select-all selects every visible item');
    action('register'); await wait(() => !get('upload').disabled && document.querySelectorAll('#explorer-rows small a').length === 2, 'Media registration');
    check(true, 'Register selected files and render Media links');
    choose('alpha.txt'); action('rename'); get('name').value = 'renamed.txt'; get('name-dialog').close('save');
    await wait(() => !get('upload').disabled && rows().some(row => row.textContent.includes('renamed.txt')), 'Rename');
    check(true, 'Rename through dialog');
    action('mkdir'); get('name').value = 'Docs'; get('name-dialog').close('save');
    await wait(() => !get('upload').disabled && rows().some(row => row.textContent.includes('Docs')), 'Create folder');
    choose('renamed.txt'); action('move');
    await wait(() => [...get('move-folders').querySelectorAll('button')].some(node => node.textContent.includes('Docs')), 'Move folder picker');
    [...get('move-folders').querySelectorAll('button')].find(node => node.textContent.includes('Docs')).click();
    await wait(() => get('move-path').textContent === '/Docs' && !get('move-dialog').querySelector('[value="move"]').disabled, 'Move destination');
    get('move-dialog').close('move');
    await wait(() => !get('upload').disabled && !rows().some(row => row.textContent.includes('renamed.txt')), 'Move');
    check(true, 'Move selected file using destination browser');
    rows().find(row => row.textContent.includes('Docs')).querySelector('.file-name').click();
    await wait(() => rows().some(row => row.textContent.includes('renamed.txt')), 'Folder navigation');
    choose('renamed.txt').querySelector('.file-name').click();
    await wait(() => get('preview-body').querySelector('pre')?.textContent === 'alpha content', 'Text preview');
    check(get('breadcrumbs').textContent.includes('Docs'), 'Breadcrumbs and optional text preview');
    const download = new FormData(); download.append('action', 'zip'); download.append('csrf_token', 'test-token'); download.append('root', 'data'); download.append('paths[]', 'Docs/renamed.txt');
    const zipResponse = await fetch('modules/explorer/api.php', { method: 'POST', body: download }); const zip = new Uint8Array(await zipResponse.arrayBuffer());
    check(zipResponse.ok && zip[0] === 80 && zip[1] === 75, 'Bulk download endpoint returns ZIP');
    window.confirm = () => true;
    action('trash'); await wait(() => !get('upload').disabled && get('status').textContent.includes('completed'), 'Trash');
    get('trash-view').click(); await wait(() => rows().some(row => row.textContent.includes('Docs/renamed.txt')), 'Trash list');
    rows()[0].querySelector('input').click(); action('restore');
    await wait(() => !get('upload').disabled && get('rows').textContent.includes('Trash is empty'), 'Restore');
    get('trash-view').click(); await wait(() => rows().some(row => row.textContent.includes('renamed.txt')), 'Restored file');
    check(true, 'Trash and restore from list controls');
    get('up').click(); await wait(() => rows().some(row => row.textContent.includes('beta.txt')), 'Up navigation');
    get('filters').elements.q.value = 'renamed'; get('filters').elements.recursive.checked = true; get('filters').requestSubmit();
    await wait(() => get('status').textContent === '1 item(s)', 'Recursive filter');
    check(rows()[0].textContent.includes('Docs'), 'Recursive search shows folder context');
    check(errors.length === 0, 'No browser script errors');
    return passes;
})()
