<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_POLL_SELECT')) define('_POLL_SELECT', 'Selecionar tema');
if (!defined('_POLL_SELECT_TOPIC')) define('_POLL_SELECT_TOPIC', '-- Selecionar tema --');
if (!defined('_POLL_SETTING_INSTRUCTION')) define('_POLL_SETTING_INSTRUCTION', 'Clique em Novo para criar uma enquete.');
if (!defined('_POLL_SETTING')) define('_POLL_SETTING', 'Enquetes');
if (!defined('_POLL_NEW_INSTRUCTION')) define('_POLL_NEW_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_POLL_EDIT_INSTRUCTION')) define('_POLL_EDIT_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_POLL_TITLE')) define('_POLL_TITLE', 'Tema');
if (!defined('_POLL_LAG')) define('_POLL_LAG', 'Intervalo entre votos');
if (!defined('_POLL_SEC')) define('_POLL_SEC', 'Seg.');
if (!defined('_POLL_OPTION')) define('_POLL_OPTION', 'Opção');
if (!defined('_POLL_TOTAL')) define('_POLL_TOTAL', 'Total de votos');
if (!defined('_POLL_RESULT')) define('_POLL_RESULT', 'Resultado');
if (!defined('_POLL_VOTE')) define('_POLL_VOTE', 'Votar');
if (!defined('_POLL')) define('_POLL', 'Enquete');
