<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_POLL_SELECT')) define('_POLL_SELECT', 'トピックを選択');
if (!defined('_POLL_SELECT_TOPIC')) define('_POLL_SELECT_TOPIC', '-- トピックを選択 --');
if (!defined('_POLL_SETTING_INSTRUCTION')) define('_POLL_SETTING_INSTRUCTION', '新規を押して投票を作成してください。');
if (!defined('_POLL_SETTING')) define('_POLL_SETTING', '投票設定');
if (!defined('_POLL_NEW_INSTRUCTION')) define('_POLL_NEW_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_POLL_EDIT_INSTRUCTION')) define('_POLL_EDIT_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_POLL_TITLE')) define('_POLL_TITLE', 'トピック');
if (!defined('_POLL_LAG')) define('_POLL_LAG', '投票間隔');
if (!defined('_POLL_SEC')) define('_POLL_SEC', '秒');
if (!defined('_POLL_OPTION')) define('_POLL_OPTION', '選択肢');
if (!defined('_POLL_TOTAL')) define('_POLL_TOTAL', '総投票数');
if (!defined('_POLL_RESULT')) define('_POLL_RESULT', '結果');
if (!defined('_POLL_VOTE')) define('_POLL_VOTE', '投票');
if (!defined('_POLL')) define('_POLL', '投票');
