<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_POLL_SELECT')) define('_POLL_SELECT', 'Thema auswählen');
if (!defined('_POLL_SELECT_TOPIC')) define('_POLL_SELECT_TOPIC', '-- Thema auswählen --');
if (!defined('_POLL_SETTING_INSTRUCTION')) define('_POLL_SETTING_INSTRUCTION', 'Klicken Sie auf Neu, um eine Umfrage zu erstellen.');
if (!defined('_POLL_SETTING')) define('_POLL_SETTING', 'Umfragen');
if (!defined('_POLL_NEW_INSTRUCTION')) define('_POLL_NEW_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_POLL_EDIT_INSTRUCTION')) define('_POLL_EDIT_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_POLL_TITLE')) define('_POLL_TITLE', 'Thema');
if (!defined('_POLL_LAG')) define('_POLL_LAG', 'Abstimmungsintervall');
if (!defined('_POLL_SEC')) define('_POLL_SEC', 'Sek.');
if (!defined('_POLL_OPTION')) define('_POLL_OPTION', 'Option');
if (!defined('_POLL_TOTAL')) define('_POLL_TOTAL', 'Stimmen insgesamt');
if (!defined('_POLL_RESULT')) define('_POLL_RESULT', 'Ergebnis');
if (!defined('_POLL_VOTE')) define('_POLL_VOTE', 'Abstimmen');
if (!defined('_POLL')) define('_POLL', 'Umfrage');
