<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_POLL_SELECT')) define('_POLL_SELECT', 'Choisir un sujet');
if (!defined('_POLL_SELECT_TOPIC')) define('_POLL_SELECT_TOPIC', '-- Choisir un sujet --');
if (!defined('_POLL_SETTING_INSTRUCTION')) define('_POLL_SETTING_INSTRUCTION', 'Cliquez sur Nouveau pour créer un sondage.');
if (!defined('_POLL_SETTING')) define('_POLL_SETTING', 'Sondages');
if (!defined('_POLL_NEW_INSTRUCTION')) define('_POLL_NEW_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_POLL_EDIT_INSTRUCTION')) define('_POLL_EDIT_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_POLL_TITLE')) define('_POLL_TITLE', 'Sujet');
if (!defined('_POLL_LAG')) define('_POLL_LAG', 'Intervalle entre votes');
if (!defined('_POLL_SEC')) define('_POLL_SEC', 'Sec.');
if (!defined('_POLL_OPTION')) define('_POLL_OPTION', 'Option');
if (!defined('_POLL_TOTAL')) define('_POLL_TOTAL', 'Total des votes');
if (!defined('_POLL_RESULT')) define('_POLL_RESULT', 'Résultats');
if (!defined('_POLL_VOTE')) define('_POLL_VOTE', 'Voter');
if (!defined('_POLL')) define('_POLL', 'Sondage');
