<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_THEME_SETTING')) define('_THEME_SETTING', 'Temas');
if (!defined('_THEME_SETTING_INSTRUCTION')) define('_THEME_SETTING_INSTRUCTION', 'Escolha um tema e clique em Salvar para aplicar ou em Voltar para retornar.');
if (!defined('_THEME_NAME')) define('_THEME_NAME', 'Nome do tema');
