<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_THEME_SETTING')) define('_THEME_SETTING', 'Themes');
if (!defined('_THEME_SETTING_INSTRUCTION')) define('_THEME_SETTING_INSTRUCTION', 'Wählen Sie ein Theme und klicken Sie auf Speichern zum Anwenden oder auf Zurück.');
if (!defined('_THEME_NAME')) define('_THEME_NAME', 'Theme-Name');
