<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_THEME_SETTING')) define('_THEME_SETTING', 'テーマ設定');
if (!defined('_THEME_SETTING_INSTRUCTION')) define('_THEME_SETTING_INSTRUCTION', 'テーマを選んで保存を押して適用するか、戻るを押して設定に戻ります。');
if (!defined('_THEME_NAME')) define('_THEME_NAME', 'テーマ名');
