<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_THEME_SETTING')) define('_THEME_SETTING', 'Temas');
if (!defined('_THEME_SETTING_INSTRUCTION')) define('_THEME_SETTING_INSTRUCTION', 'Elige un tema y pulsa Guardar para aplicarlo o Volver para regresar.');
if (!defined('_THEME_NAME')) define('_THEME_NAME', 'Nombre del tema');
