<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_THEME_SETTING')) define('_THEME_SETTING', 'Thèmes');
if (!defined('_THEME_SETTING_INSTRUCTION')) define('_THEME_SETTING_INSTRUCTION', 'Choisissez un thème et cliquez sur Enregistrer pour l’appliquer ou sur Retour.');
if (!defined('_THEME_NAME')) define('_THEME_NAME', 'Nom du thème');
