<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_LANGUAGE_SETTING')) define('_LANGUAGE_SETTING', '言語設定');
if (!defined('_LANGUAGE_SETTING_INSTRUCTION')) define('_LANGUAGE_SETTING_INSTRUCTION', '表示言語を選択してください。');
if (!defined('_LANGUAGE_NAME')) define('_LANGUAGE_NAME', '言語を選択');
