<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_LANGUAGE_SETTING')) define('_LANGUAGE_SETTING', 'Configurações de idioma');
if (!defined('_LANGUAGE_SETTING_INSTRUCTION')) define('_LANGUAGE_SETTING_INSTRUCTION', 'Escolha o idioma da interface.');
if (!defined('_LANGUAGE_NAME')) define('_LANGUAGE_NAME', 'Selecionar idioma');
