<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_MEDIA_SETTING')) define('_MEDIA_SETTING', 'Mediathek');
if (!defined('_MEDIA_SETTING_INSTRUCTION')) define('_MEDIA_SETTING_INSTRUCTION', 'Laden Sie Dateien hoch, suchen und filtern Sie sie. Wählen Sie eine Datei, um Titel, Beschriftung und Alternativtext zu bearbeiten.');
if (!defined('_MEDIA_UPLOAD')) define('_MEDIA_UPLOAD', 'Hochladen');
if (!defined('_MEDIA_UPLOAD_FAILED')) define('_MEDIA_UPLOAD_FAILED', 'Upload fehlgeschlagen. Prüfen Sie den zulässigen Dateityp (jpg, jpeg, png, gif, webp, pdf, doc, docx, xls, xlsx, zip, txt).');
if (!defined('_MEDIA_ALT_TEXT')) define('_MEDIA_ALT_TEXT', 'Alternativtext (optional)');
if (!defined('_MEDIA_STORAGE_NOT_WRITABLE')) define('_MEDIA_STORAGE_NOT_WRITABLE', 'PHP kann nicht in datacenter/media schreiben. Bitten Sie Ihren Hoster, die Berechtigungen vor dem Upload zu korrigieren.');
