<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_MEDIA_SETTING')) define('_MEDIA_SETTING', 'Biblioteca multimedia');
if (!defined('_MEDIA_SETTING_INSTRUCTION')) define('_MEDIA_SETTING_INSTRUCTION', 'Sube, busca y filtra archivos. Selecciona un archivo para editar el título, la leyenda y el texto alternativo.');
if (!defined('_MEDIA_UPLOAD')) define('_MEDIA_UPLOAD', 'Subir');
if (!defined('_MEDIA_UPLOAD_FAILED')) define('_MEDIA_UPLOAD_FAILED', 'Error al subir. Comprueba el formato permitido (jpg, jpeg, png, gif, webp, pdf, doc, docx, xls, xlsx, zip, txt).');
if (!defined('_MEDIA_ALT_TEXT')) define('_MEDIA_ALT_TEXT', 'Texto alternativo (opcional)');
if (!defined('_MEDIA_STORAGE_NOT_WRITABLE')) define('_MEDIA_STORAGE_NOT_WRITABLE', 'PHP no puede escribir en datacenter/media. Pide al proveedor que corrija los permisos antes de subir archivos.');
