<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_MEDIA_SETTING')) define('_MEDIA_SETTING', 'メディアライブラリ');
if (!defined('_MEDIA_SETTING_INSTRUCTION')) define('_MEDIA_SETTING_INSTRUCTION', 'ファイルのアップロード、検索、絞り込みができます。ファイル名を選択してタイトル、キャプション、代替テキストを編集します。');
if (!defined('_MEDIA_UPLOAD')) define('_MEDIA_UPLOAD', 'アップロード');
if (!defined('_MEDIA_UPLOAD_FAILED')) define('_MEDIA_UPLOAD_FAILED', 'アップロードに失敗しました。許可されている形式（jpg, jpeg, png, gif, webp, pdf, doc, docx, xls, xlsx, zip, txt）を確認してください。');
if (!defined('_MEDIA_ALT_TEXT')) define('_MEDIA_ALT_TEXT', '代替テキスト（任意）');
if (!defined('_MEDIA_STORAGE_NOT_WRITABLE')) define('_MEDIA_STORAGE_NOT_WRITABLE', 'PHPがdatacenter/mediaに書き込めません。アップロード前にホスティング管理者に権限の修正を依頼してください。');
