<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_MEDIA_SETTING')) define('_MEDIA_SETTING', 'Biblioteca de mídia');
if (!defined('_MEDIA_SETTING_INSTRUCTION')) define('_MEDIA_SETTING_INSTRUCTION', 'Envie, pesquise e filtre arquivos. Selecione um arquivo para editar título, legenda e texto alternativo.');
if (!defined('_MEDIA_UPLOAD')) define('_MEDIA_UPLOAD', 'Enviar');
if (!defined('_MEDIA_UPLOAD_FAILED')) define('_MEDIA_UPLOAD_FAILED', 'Falha no envio. Verifique o tipo permitido (jpg, jpeg, png, gif, webp, pdf, doc, docx, xls, xlsx, zip, txt).');
if (!defined('_MEDIA_ALT_TEXT')) define('_MEDIA_ALT_TEXT', 'Texto alternativo (opcional)');
if (!defined('_MEDIA_STORAGE_NOT_WRITABLE')) define('_MEDIA_STORAGE_NOT_WRITABLE', 'O PHP não pode gravar em datacenter/media. Peça ao provedor para corrigir as permissões antes de enviar arquivos.');
