<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_MEDIA_SETTING')) define('_MEDIA_SETTING', 'Médiathèque');
if (!defined('_MEDIA_SETTING_INSTRUCTION')) define('_MEDIA_SETTING_INSTRUCTION', 'Téléversez, recherchez et filtrez les fichiers. Choisissez un fichier pour modifier son titre, sa légende et son texte alternatif.');
if (!defined('_MEDIA_UPLOAD')) define('_MEDIA_UPLOAD', 'Téléverser');
if (!defined('_MEDIA_UPLOAD_FAILED')) define('_MEDIA_UPLOAD_FAILED', 'Échec du téléversement. Vérifiez le type autorisé (jpg, jpeg, png, gif, webp, pdf, doc, docx, xls, xlsx, zip, txt).');
if (!defined('_MEDIA_ALT_TEXT')) define('_MEDIA_ALT_TEXT', 'Texte alternatif (facultatif)');
if (!defined('_MEDIA_STORAGE_NOT_WRITABLE')) define('_MEDIA_STORAGE_NOT_WRITABLE', 'PHP ne peut pas écrire dans datacenter/media. Demandez à votre hébergeur de corriger les permissions avant de téléverser.');
