<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_CTYPE_SETTING')) define('_CTYPE_SETTING', 'Tipos de conteúdo');
if (!defined('_CTYPE_SETTING_INSTRUCTION')) define('_CTYPE_SETTING_INSTRUCTION', 'Defina tipos de conteúdo com seus campos, como produtos, depoimentos ou projetos. Clique em Novo para criar um tipo.');
if (!defined('_CTYPE_TITLE')) define('_CTYPE_TITLE', 'Título do tipo');
if (!defined('_CTYPE_SLUG')) define('_CTYPE_SLUG', 'Identificador da URL');
if (!defined('_CTYPE_FIELDS')) define('_CTYPE_FIELDS', 'Campos');
if (!defined('_CTYPE_NEW')) define('_CTYPE_NEW', 'Novo tipo de conteúdo');
if (!defined('_CTYPE_NEW_INSTRUCTION')) define('_CTYPE_NEW_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_CTYPE_EDIT')) define('_CTYPE_EDIT', 'Editar tipo de conteúdo');
if (!defined('_CTYPE_EDIT_INSTRUCTION')) define('_CTYPE_EDIT_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_CTYPE_NOT_FOUND')) define('_CTYPE_NOT_FOUND', 'Tipo de conteúdo não encontrado');
if (!defined('_CTYPE_MANAGE_FIELDS')) define('_CTYPE_MANAGE_FIELDS', 'Gerenciar campos');
if (!defined('_CTYPE_MANAGE_ITEMS')) define('_CTYPE_MANAGE_ITEMS', 'Gerenciar itens');
if (!defined('_CTYPE_FIELDS_INSTRUCTION')) define('_CTYPE_FIELDS_INSTRUCTION', 'Adicione os campos deste tipo de conteúdo e gerencie os itens que os utilizam.');
if (!defined('_CTYPE_FIELD_LABEL')) define('_CTYPE_FIELD_LABEL', 'Rótulo do campo');
if (!defined('_CTYPE_FIELD_TYPE')) define('_CTYPE_FIELD_TYPE', 'Tipo do campo');
if (!defined('_CTYPE_FIELD_OPTIONS')) define('_CTYPE_FIELD_OPTIONS', 'Opções (para seleção)');
if (!defined('_CTYPE_FIELD_REQUIRED')) define('_CTYPE_FIELD_REQUIRED', 'Obrigatório');
if (!defined('_CTYPE_FIELD_NEW')) define('_CTYPE_FIELD_NEW', 'Adicionar campo');
if (!defined('_CTYPE_ITEMS_INSTRUCTION')) define('_CTYPE_ITEMS_INSTRUCTION', 'Gerencie os itens deste tipo de conteúdo.');
if (!defined('_CTYPE_ITEM_TITLE')) define('_CTYPE_ITEM_TITLE', 'Título do item');
if (!defined('_CTYPE_ITEM_NEW')) define('_CTYPE_ITEM_NEW', 'Novo item');
if (!defined('_CTYPE_ITEM_EDIT')) define('_CTYPE_ITEM_EDIT', 'Editar item');
if (!defined('_CTYPE_ITEM_NOT_FOUND')) define('_CTYPE_ITEM_NOT_FOUND', 'Item não encontrado');
if (!defined('_CTYPE_NO_ITEMS')) define('_CTYPE_NO_ITEMS', 'Nenhum item encontrado.');
if (!defined('_CTYPE_NO_PERMISSION')) define('_CTYPE_NO_PERMISSION', 'Você não tem permissão para realizar esta ação.');
