<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_CTYPE_SETTING')) define('_CTYPE_SETTING', 'Tipos de contenido');
if (!defined('_CTYPE_SETTING_INSTRUCTION')) define('_CTYPE_SETTING_INSTRUCTION', 'Define tipos de contenido con tus propios campos, como productos, testimonios o proyectos. Pulsa Nuevo para crear un tipo.');
if (!defined('_CTYPE_TITLE')) define('_CTYPE_TITLE', 'Título del tipo');
if (!defined('_CTYPE_SLUG')) define('_CTYPE_SLUG', 'Identificador de URL');
if (!defined('_CTYPE_FIELDS')) define('_CTYPE_FIELDS', 'Campos');
if (!defined('_CTYPE_NEW')) define('_CTYPE_NEW', 'Nuevo tipo de contenido');
if (!defined('_CTYPE_NEW_INSTRUCTION')) define('_CTYPE_NEW_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_CTYPE_EDIT')) define('_CTYPE_EDIT', 'Editar tipo de contenido');
if (!defined('_CTYPE_EDIT_INSTRUCTION')) define('_CTYPE_EDIT_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_CTYPE_NOT_FOUND')) define('_CTYPE_NOT_FOUND', 'Tipo de contenido no encontrado');
if (!defined('_CTYPE_MANAGE_FIELDS')) define('_CTYPE_MANAGE_FIELDS', 'Gestionar campos');
if (!defined('_CTYPE_MANAGE_ITEMS')) define('_CTYPE_MANAGE_ITEMS', 'Gestionar elementos');
if (!defined('_CTYPE_FIELDS_INSTRUCTION')) define('_CTYPE_FIELDS_INSTRUCTION', 'Añade los campos de este tipo de contenido y gestiona los elementos que los utilizan.');
if (!defined('_CTYPE_FIELD_LABEL')) define('_CTYPE_FIELD_LABEL', 'Etiqueta del campo');
if (!defined('_CTYPE_FIELD_TYPE')) define('_CTYPE_FIELD_TYPE', 'Tipo de campo');
if (!defined('_CTYPE_FIELD_OPTIONS')) define('_CTYPE_FIELD_OPTIONS', 'Opciones (para selección)');
if (!defined('_CTYPE_FIELD_REQUIRED')) define('_CTYPE_FIELD_REQUIRED', 'Obligatorio');
if (!defined('_CTYPE_FIELD_NEW')) define('_CTYPE_FIELD_NEW', 'Añadir campo');
if (!defined('_CTYPE_ITEMS_INSTRUCTION')) define('_CTYPE_ITEMS_INSTRUCTION', 'Gestiona los elementos de este tipo de contenido.');
if (!defined('_CTYPE_ITEM_TITLE')) define('_CTYPE_ITEM_TITLE', 'Título del elemento');
if (!defined('_CTYPE_ITEM_NEW')) define('_CTYPE_ITEM_NEW', 'Nuevo elemento');
if (!defined('_CTYPE_ITEM_EDIT')) define('_CTYPE_ITEM_EDIT', 'Editar elemento');
if (!defined('_CTYPE_ITEM_NOT_FOUND')) define('_CTYPE_ITEM_NOT_FOUND', 'Elemento no encontrado');
if (!defined('_CTYPE_NO_ITEMS')) define('_CTYPE_NO_ITEMS', 'No se encontraron elementos.');
if (!defined('_CTYPE_NO_PERMISSION')) define('_CTYPE_NO_PERMISSION', 'No tienes permiso para realizar esta acción.');
