<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_CTYPE_SETTING')) define('_CTYPE_SETTING', 'コンテンツタイプ');
if (!defined('_CTYPE_SETTING_INSTRUCTION')) define('_CTYPE_SETTING_INSTRUCTION', '商品、お客様の声、制作実績など、独自のフィールドを持つコンテンツタイプを定義します。新規を押して作成してください。');
if (!defined('_CTYPE_TITLE')) define('_CTYPE_TITLE', 'タイプのタイトル');
if (!defined('_CTYPE_SLUG')) define('_CTYPE_SLUG', 'URLスラッグ');
if (!defined('_CTYPE_FIELDS')) define('_CTYPE_FIELDS', 'フィールド');
if (!defined('_CTYPE_NEW')) define('_CTYPE_NEW', 'コンテンツタイプを追加');
if (!defined('_CTYPE_NEW_INSTRUCTION')) define('_CTYPE_NEW_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_CTYPE_EDIT')) define('_CTYPE_EDIT', 'コンテンツタイプを編集');
if (!defined('_CTYPE_EDIT_INSTRUCTION')) define('_CTYPE_EDIT_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_CTYPE_NOT_FOUND')) define('_CTYPE_NOT_FOUND', 'コンテンツタイプが見つかりません');
if (!defined('_CTYPE_MANAGE_FIELDS')) define('_CTYPE_MANAGE_FIELDS', 'フィールドを管理');
if (!defined('_CTYPE_MANAGE_ITEMS')) define('_CTYPE_MANAGE_ITEMS', '項目を管理');
if (!defined('_CTYPE_FIELDS_INSTRUCTION')) define('_CTYPE_FIELDS_INSTRUCTION', 'このコンテンツタイプのフィールドを追加して、それを使う項目を管理します。');
if (!defined('_CTYPE_FIELD_LABEL')) define('_CTYPE_FIELD_LABEL', 'フィールドのラベル');
if (!defined('_CTYPE_FIELD_TYPE')) define('_CTYPE_FIELD_TYPE', 'フィールドの種類');
if (!defined('_CTYPE_FIELD_OPTIONS')) define('_CTYPE_FIELD_OPTIONS', '選択肢（選択フィールド用）');
if (!defined('_CTYPE_FIELD_REQUIRED')) define('_CTYPE_FIELD_REQUIRED', '必須');
if (!defined('_CTYPE_FIELD_NEW')) define('_CTYPE_FIELD_NEW', 'フィールドを追加');
if (!defined('_CTYPE_ITEMS_INSTRUCTION')) define('_CTYPE_ITEMS_INSTRUCTION', 'このコンテンツタイプの項目を管理します。');
if (!defined('_CTYPE_ITEM_TITLE')) define('_CTYPE_ITEM_TITLE', '項目のタイトル');
if (!defined('_CTYPE_ITEM_NEW')) define('_CTYPE_ITEM_NEW', '項目を追加');
if (!defined('_CTYPE_ITEM_EDIT')) define('_CTYPE_ITEM_EDIT', '項目を編集');
if (!defined('_CTYPE_ITEM_NOT_FOUND')) define('_CTYPE_ITEM_NOT_FOUND', '項目が見つかりません');
if (!defined('_CTYPE_NO_ITEMS')) define('_CTYPE_NO_ITEMS', '項目がありません。');
if (!defined('_CTYPE_NO_PERMISSION')) define('_CTYPE_NO_PERMISSION', 'この操作を行う権限がありません。');
