<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_CTYPE_SETTING')) define('_CTYPE_SETTING', 'Inhaltstypen');
if (!defined('_CTYPE_SETTING_INSTRUCTION')) define('_CTYPE_SETTING_INSTRUCTION', 'Definieren Sie Inhaltstypen mit eigenen Feldern, etwa Produkte, Referenzen oder Projekte. Klicken Sie auf Neu, um einen Typ zu erstellen.');
if (!defined('_CTYPE_TITLE')) define('_CTYPE_TITLE', 'Typname');
if (!defined('_CTYPE_SLUG')) define('_CTYPE_SLUG', 'URL-Kurzname');
if (!defined('_CTYPE_FIELDS')) define('_CTYPE_FIELDS', 'Felder');
if (!defined('_CTYPE_NEW')) define('_CTYPE_NEW', 'Neuer Inhaltstyp');
if (!defined('_CTYPE_NEW_INSTRUCTION')) define('_CTYPE_NEW_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_CTYPE_EDIT')) define('_CTYPE_EDIT', 'Inhaltstyp bearbeiten');
if (!defined('_CTYPE_EDIT_INSTRUCTION')) define('_CTYPE_EDIT_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_CTYPE_NOT_FOUND')) define('_CTYPE_NOT_FOUND', 'Inhaltstyp nicht gefunden');
if (!defined('_CTYPE_MANAGE_FIELDS')) define('_CTYPE_MANAGE_FIELDS', 'Felder verwalten');
if (!defined('_CTYPE_MANAGE_ITEMS')) define('_CTYPE_MANAGE_ITEMS', 'Einträge verwalten');
if (!defined('_CTYPE_FIELDS_INSTRUCTION')) define('_CTYPE_FIELDS_INSTRUCTION', 'Fügen Sie die Felder dieses Inhaltstyps hinzu und verwalten Sie damit die Einträge.');
if (!defined('_CTYPE_FIELD_LABEL')) define('_CTYPE_FIELD_LABEL', 'Feldbezeichnung');
if (!defined('_CTYPE_FIELD_TYPE')) define('_CTYPE_FIELD_TYPE', 'Feldtyp');
if (!defined('_CTYPE_FIELD_OPTIONS')) define('_CTYPE_FIELD_OPTIONS', 'Optionen (für Auswahl)');
if (!defined('_CTYPE_FIELD_REQUIRED')) define('_CTYPE_FIELD_REQUIRED', 'Erforderlich');
if (!defined('_CTYPE_FIELD_NEW')) define('_CTYPE_FIELD_NEW', 'Feld hinzufügen');
if (!defined('_CTYPE_ITEMS_INSTRUCTION')) define('_CTYPE_ITEMS_INSTRUCTION', 'Verwalten Sie die Einträge dieses Inhaltstyps.');
if (!defined('_CTYPE_ITEM_TITLE')) define('_CTYPE_ITEM_TITLE', 'Eintragstitel');
if (!defined('_CTYPE_ITEM_NEW')) define('_CTYPE_ITEM_NEW', 'Neuer Eintrag');
if (!defined('_CTYPE_ITEM_EDIT')) define('_CTYPE_ITEM_EDIT', 'Eintrag bearbeiten');
if (!defined('_CTYPE_ITEM_NOT_FOUND')) define('_CTYPE_ITEM_NOT_FOUND', 'Eintrag nicht gefunden');
if (!defined('_CTYPE_NO_ITEMS')) define('_CTYPE_NO_ITEMS', 'Keine Einträge gefunden.');
if (!defined('_CTYPE_NO_PERMISSION')) define('_CTYPE_NO_PERMISSION', 'Sie haben keine Berechtigung für diese Aktion.');
