<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_CTYPE_SETTING')) define('_CTYPE_SETTING', 'Types de contenu');
if (!defined('_CTYPE_SETTING_INSTRUCTION')) define('_CTYPE_SETTING_INSTRUCTION', 'Définissez des types de contenu avec vos champs, comme des produits, témoignages ou projets. Cliquez sur Nouveau pour créer un type.');
if (!defined('_CTYPE_TITLE')) define('_CTYPE_TITLE', 'Titre du type');
if (!defined('_CTYPE_SLUG')) define('_CTYPE_SLUG', 'Identifiant d’URL');
if (!defined('_CTYPE_FIELDS')) define('_CTYPE_FIELDS', 'Champs');
if (!defined('_CTYPE_NEW')) define('_CTYPE_NEW', 'Nouveau type de contenu');
if (!defined('_CTYPE_NEW_INSTRUCTION')) define('_CTYPE_NEW_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_CTYPE_EDIT')) define('_CTYPE_EDIT', 'Modifier le type de contenu');
if (!defined('_CTYPE_EDIT_INSTRUCTION')) define('_CTYPE_EDIT_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_CTYPE_NOT_FOUND')) define('_CTYPE_NOT_FOUND', 'Type de contenu introuvable');
if (!defined('_CTYPE_MANAGE_FIELDS')) define('_CTYPE_MANAGE_FIELDS', 'Gérer les champs');
if (!defined('_CTYPE_MANAGE_ITEMS')) define('_CTYPE_MANAGE_ITEMS', 'Gérer les éléments');
if (!defined('_CTYPE_FIELDS_INSTRUCTION')) define('_CTYPE_FIELDS_INSTRUCTION', 'Ajoutez les champs de ce type de contenu puis gérez les éléments qui les utilisent.');
if (!defined('_CTYPE_FIELD_LABEL')) define('_CTYPE_FIELD_LABEL', 'Libellé du champ');
if (!defined('_CTYPE_FIELD_TYPE')) define('_CTYPE_FIELD_TYPE', 'Type de champ');
if (!defined('_CTYPE_FIELD_OPTIONS')) define('_CTYPE_FIELD_OPTIONS', 'Options (pour une liste)');
if (!defined('_CTYPE_FIELD_REQUIRED')) define('_CTYPE_FIELD_REQUIRED', 'Obligatoire');
if (!defined('_CTYPE_FIELD_NEW')) define('_CTYPE_FIELD_NEW', 'Ajouter un champ');
if (!defined('_CTYPE_ITEMS_INSTRUCTION')) define('_CTYPE_ITEMS_INSTRUCTION', 'Gérez les éléments de ce type de contenu.');
if (!defined('_CTYPE_ITEM_TITLE')) define('_CTYPE_ITEM_TITLE', 'Titre de l’élément');
if (!defined('_CTYPE_ITEM_NEW')) define('_CTYPE_ITEM_NEW', 'Nouvel élément');
if (!defined('_CTYPE_ITEM_EDIT')) define('_CTYPE_ITEM_EDIT', 'Modifier l’élément');
if (!defined('_CTYPE_ITEM_NOT_FOUND')) define('_CTYPE_ITEM_NOT_FOUND', 'Élément introuvable');
if (!defined('_CTYPE_NO_ITEMS')) define('_CTYPE_NO_ITEMS', 'Aucun élément trouvé.');
if (!defined('_CTYPE_NO_PERMISSION')) define('_CTYPE_NO_PERMISSION', 'Vous n’avez pas l’autorisation d’effectuer cette action.');
