<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_BLOCK_SETTING')) define('_BLOCK_SETTING', 'Blocos');
if (!defined('_BLOCK_SETTING_INSTRUCTION')) define('_BLOCK_SETTING_INSTRUCTION', 'Clique em Novo para criar um bloco ou em Voltar para retornar às configurações.');
if (!defined('_BLOCK_TITLE')) define('_BLOCK_TITLE', 'Título');
if (!defined('_BLOCK_NAME')) define('_BLOCK_NAME', 'Nome');
if (!defined('_BLOCK_POSITION')) define('_BLOCK_POSITION', 'Posição');
if (!defined('_BLOCK_TYPE_INSTRUCTION')) define('_BLOCK_TYPE_INSTRUCTION', 'Escolha o tipo de bloco e clique em Salvar para criá-lo.');
if (!defined('_BLOCK_TYPE')) define('_BLOCK_TYPE', 'Tipo de bloco');
if (!defined('_BLOCK_CONTENT_TYPE')) define('_BLOCK_CONTENT_TYPE', 'Tipo de conteúdo');
if (!defined('_BLOCK_RSS')) define('_BLOCK_RSS', 'RSS');
if (!defined('_BLOCK_UPLOAD')) define('_BLOCK_UPLOAD', 'Enviar bloco');
if (!defined('_BLOCK_NEW_INSTRUCTION')) define('_BLOCK_NEW_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_BLOCK_EDIT_INSTRUCTION')) define('_BLOCK_EDIT_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_BLOCK_CONTENT')) define('_BLOCK_CONTENT', 'Conteúdo');
if (!defined('_BLOCK_URL')) define('_BLOCK_URL', 'URL');
if (!defined('_BLOCK_REFRESH')) define('_BLOCK_REFRESH', 'Atualizar');
if (!defined('_BLOCK_FILE')) define('_BLOCK_FILE', 'Procurar');
if (!defined('_BLOCK_EXTRACTED_PATH')) define('_BLOCK_EXTRACTED_PATH', 'Caminho do bloco existente');
if (!defined('_BLOCK_PATH_NOT_EXIST')) define('_BLOCK_PATH_NOT_EXIST', 'O caminho do bloco não existe.');
