<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_BLOCK_SETTING')) define('_BLOCK_SETTING', 'Blocs');
if (!defined('_BLOCK_SETTING_INSTRUCTION')) define('_BLOCK_SETTING_INSTRUCTION', 'Cliquez sur Nouveau pour créer un bloc ou sur Retour pour revenir aux paramètres.');
if (!defined('_BLOCK_TITLE')) define('_BLOCK_TITLE', 'Titre');
if (!defined('_BLOCK_NAME')) define('_BLOCK_NAME', 'Nom');
if (!defined('_BLOCK_POSITION')) define('_BLOCK_POSITION', 'Position');
if (!defined('_BLOCK_TYPE_INSTRUCTION')) define('_BLOCK_TYPE_INSTRUCTION', 'Choisissez le type de bloc puis cliquez sur Enregistrer pour le créer.');
if (!defined('_BLOCK_TYPE')) define('_BLOCK_TYPE', 'Type de bloc');
if (!defined('_BLOCK_CONTENT_TYPE')) define('_BLOCK_CONTENT_TYPE', 'Type de contenu');
if (!defined('_BLOCK_RSS')) define('_BLOCK_RSS', 'RSS');
if (!defined('_BLOCK_UPLOAD')) define('_BLOCK_UPLOAD', 'Téléverser un bloc');
if (!defined('_BLOCK_NEW_INSTRUCTION')) define('_BLOCK_NEW_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_BLOCK_EDIT_INSTRUCTION')) define('_BLOCK_EDIT_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_BLOCK_CONTENT')) define('_BLOCK_CONTENT', 'Contenu');
if (!defined('_BLOCK_URL')) define('_BLOCK_URL', 'URL');
if (!defined('_BLOCK_REFRESH')) define('_BLOCK_REFRESH', 'Actualiser');
if (!defined('_BLOCK_FILE')) define('_BLOCK_FILE', 'Parcourir');
if (!defined('_BLOCK_EXTRACTED_PATH')) define('_BLOCK_EXTRACTED_PATH', 'Chemin du bloc existant');
if (!defined('_BLOCK_PATH_NOT_EXIST')) define('_BLOCK_PATH_NOT_EXIST', 'Le chemin du bloc n’existe pas.');
