<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_BLOCK_SETTING')) define('_BLOCK_SETTING', 'Bloques');
if (!defined('_BLOCK_SETTING_INSTRUCTION')) define('_BLOCK_SETTING_INSTRUCTION', 'Pulsa Nuevo para crear un bloque o Volver para regresar a la configuración.');
if (!defined('_BLOCK_TITLE')) define('_BLOCK_TITLE', 'Título');
if (!defined('_BLOCK_NAME')) define('_BLOCK_NAME', 'Nombre');
if (!defined('_BLOCK_POSITION')) define('_BLOCK_POSITION', 'Posición');
if (!defined('_BLOCK_TYPE_INSTRUCTION')) define('_BLOCK_TYPE_INSTRUCTION', 'Elige el tipo de bloque y pulsa Guardar para crearlo.');
if (!defined('_BLOCK_TYPE')) define('_BLOCK_TYPE', 'Tipo de bloque');
if (!defined('_BLOCK_CONTENT_TYPE')) define('_BLOCK_CONTENT_TYPE', 'Tipo de contenido');
if (!defined('_BLOCK_RSS')) define('_BLOCK_RSS', 'RSS');
if (!defined('_BLOCK_UPLOAD')) define('_BLOCK_UPLOAD', 'Subir bloque');
if (!defined('_BLOCK_NEW_INSTRUCTION')) define('_BLOCK_NEW_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_BLOCK_EDIT_INSTRUCTION')) define('_BLOCK_EDIT_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_BLOCK_CONTENT')) define('_BLOCK_CONTENT', 'Contenido');
if (!defined('_BLOCK_URL')) define('_BLOCK_URL', 'URL');
if (!defined('_BLOCK_REFRESH')) define('_BLOCK_REFRESH', 'Actualizar');
if (!defined('_BLOCK_FILE')) define('_BLOCK_FILE', 'Examinar');
if (!defined('_BLOCK_EXTRACTED_PATH')) define('_BLOCK_EXTRACTED_PATH', 'Ruta del bloque existente');
if (!defined('_BLOCK_PATH_NOT_EXIST')) define('_BLOCK_PATH_NOT_EXIST', 'La ruta del bloque no existe.');
