<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_BLOCK_SETTING')) define('_BLOCK_SETTING', 'Blöcke');
if (!defined('_BLOCK_SETTING_INSTRUCTION')) define('_BLOCK_SETTING_INSTRUCTION', 'Klicken Sie auf Neu für einen Block oder auf Zurück für die Einstellungen.');
if (!defined('_BLOCK_TITLE')) define('_BLOCK_TITLE', 'Titel');
if (!defined('_BLOCK_NAME')) define('_BLOCK_NAME', 'Name');
if (!defined('_BLOCK_POSITION')) define('_BLOCK_POSITION', 'Position');
if (!defined('_BLOCK_TYPE_INSTRUCTION')) define('_BLOCK_TYPE_INSTRUCTION', 'Wählen Sie den Blocktyp und klicken Sie auf Speichern, um ihn zu erstellen.');
if (!defined('_BLOCK_TYPE')) define('_BLOCK_TYPE', 'Blocktyp');
if (!defined('_BLOCK_CONTENT_TYPE')) define('_BLOCK_CONTENT_TYPE', 'Inhaltstyp');
if (!defined('_BLOCK_RSS')) define('_BLOCK_RSS', 'RSS');
if (!defined('_BLOCK_UPLOAD')) define('_BLOCK_UPLOAD', 'Block hochladen');
if (!defined('_BLOCK_NEW_INSTRUCTION')) define('_BLOCK_NEW_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_BLOCK_EDIT_INSTRUCTION')) define('_BLOCK_EDIT_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_BLOCK_CONTENT')) define('_BLOCK_CONTENT', 'Inhalt');
if (!defined('_BLOCK_URL')) define('_BLOCK_URL', 'URL');
if (!defined('_BLOCK_REFRESH')) define('_BLOCK_REFRESH', 'Aktualisieren');
if (!defined('_BLOCK_FILE')) define('_BLOCK_FILE', 'Durchsuchen');
if (!defined('_BLOCK_EXTRACTED_PATH')) define('_BLOCK_EXTRACTED_PATH', 'Pfad zum vorhandenen Block');
if (!defined('_BLOCK_PATH_NOT_EXIST')) define('_BLOCK_PATH_NOT_EXIST', 'Der Blockpfad existiert nicht.');
