<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_BLOCK_SETTING')) define('_BLOCK_SETTING', 'ブロック設定');
if (!defined('_BLOCK_SETTING_INSTRUCTION')) define('_BLOCK_SETTING_INSTRUCTION', '新規を押してブロックを作成するか、戻るを押して設定に戻ります。');
if (!defined('_BLOCK_TITLE')) define('_BLOCK_TITLE', 'タイトル');
if (!defined('_BLOCK_NAME')) define('_BLOCK_NAME', '名前');
if (!defined('_BLOCK_POSITION')) define('_BLOCK_POSITION', '位置');
if (!defined('_BLOCK_TYPE_INSTRUCTION')) define('_BLOCK_TYPE_INSTRUCTION', 'ブロックの種類を選び、保存を押して作成してください。');
if (!defined('_BLOCK_TYPE')) define('_BLOCK_TYPE', 'ブロックの種類');
if (!defined('_BLOCK_CONTENT_TYPE')) define('_BLOCK_CONTENT_TYPE', 'コンテンツタイプ');
if (!defined('_BLOCK_RSS')) define('_BLOCK_RSS', 'RSS');
if (!defined('_BLOCK_UPLOAD')) define('_BLOCK_UPLOAD', 'ブロックをアップロード');
if (!defined('_BLOCK_NEW_INSTRUCTION')) define('_BLOCK_NEW_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_BLOCK_EDIT_INSTRUCTION')) define('_BLOCK_EDIT_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_BLOCK_CONTENT')) define('_BLOCK_CONTENT', 'コンテンツ');
if (!defined('_BLOCK_URL')) define('_BLOCK_URL', 'URL');
if (!defined('_BLOCK_REFRESH')) define('_BLOCK_REFRESH', '更新');
if (!defined('_BLOCK_FILE')) define('_BLOCK_FILE', '参照');
if (!defined('_BLOCK_EXTRACTED_PATH')) define('_BLOCK_EXTRACTED_PATH', '既存ブロックのパス');
if (!defined('_BLOCK_PATH_NOT_EXIST')) define('_BLOCK_PATH_NOT_EXIST', 'ブロックのパスが存在しません。');
