<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_MENU_SETTING')) define('_MENU_SETTING', 'Menus');
if (!defined('_MENU_SETTING_INSTRUCTION')) define('_MENU_SETTING_INSTRUCTION', 'Clique em Novo para criar um menu ou em Voltar para retornar às configurações.');
if (!defined('_MENU_TITLE')) define('_MENU_TITLE', 'Título');
if (!defined('_MENU_TYPE')) define('_MENU_TYPE', 'Tipo');
if (!defined('_MENU_TYPE_INSTRUCTION')) define('_MENU_TYPE_INSTRUCTION', 'Escolha o tipo de menu e clique em Novo para criá-lo.');
if (!defined('_MENU_CONTENT')) define('_MENU_CONTENT', 'Conteúdo');
if (!defined('_MENU_MODULE')) define('_MENU_MODULE', 'Módulo');
if (!defined('_MENU_LINK')) define('_MENU_LINK', 'Link');
if (!defined('_MENU_NEW_INSTRUCTION')) define('_MENU_NEW_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_MENU_TARGET')) define('_MENU_TARGET', 'Destino');
if (!defined('_NONE')) define('_NONE', 'Nenhum');
if (!defined('_MENU_PARENT')) define('_MENU_PARENT', 'Item pai');
if (!defined('_MENU_MODNAME')) define('_MENU_MODNAME', 'Módulo');
if (!defined('_MENU_EDIT_INSTRUCTION')) define('_MENU_EDIT_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_MENU_URL')) define('_MENU_URL', 'URL');
if (!defined('_MENU_NONE')) define('_MENU_NONE', 'Nenhum');
