<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_MENU_SETTING')) define('_MENU_SETTING', 'Menus');
if (!defined('_MENU_SETTING_INSTRUCTION')) define('_MENU_SETTING_INSTRUCTION', 'Cliquez sur Nouveau pour créer un menu ou sur Retour pour revenir aux paramètres.');
if (!defined('_MENU_TITLE')) define('_MENU_TITLE', 'Titre');
if (!defined('_MENU_TYPE')) define('_MENU_TYPE', 'Type');
if (!defined('_MENU_TYPE_INSTRUCTION')) define('_MENU_TYPE_INSTRUCTION', 'Choisissez le type de menu puis cliquez sur Nouveau pour le créer.');
if (!defined('_MENU_CONTENT')) define('_MENU_CONTENT', 'Contenu');
if (!defined('_MENU_MODULE')) define('_MENU_MODULE', 'Module');
if (!defined('_MENU_LINK')) define('_MENU_LINK', 'Lien');
if (!defined('_MENU_NEW_INSTRUCTION')) define('_MENU_NEW_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_MENU_TARGET')) define('_MENU_TARGET', 'Cible');
if (!defined('_NONE')) define('_NONE', 'Aucun');
if (!defined('_MENU_PARENT')) define('_MENU_PARENT', 'Parent');
if (!defined('_MENU_MODNAME')) define('_MENU_MODNAME', 'Module');
if (!defined('_MENU_EDIT_INSTRUCTION')) define('_MENU_EDIT_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_MENU_URL')) define('_MENU_URL', 'URL');
if (!defined('_MENU_NONE')) define('_MENU_NONE', 'Aucun');
