<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_MENU_SETTING')) define('_MENU_SETTING', 'Menüs');
if (!defined('_MENU_SETTING_INSTRUCTION')) define('_MENU_SETTING_INSTRUCTION', 'Klicken Sie auf Neu für ein Menü oder auf Zurück für die Einstellungen.');
if (!defined('_MENU_TITLE')) define('_MENU_TITLE', 'Titel');
if (!defined('_MENU_TYPE')) define('_MENU_TYPE', 'Typ');
if (!defined('_MENU_TYPE_INSTRUCTION')) define('_MENU_TYPE_INSTRUCTION', 'Wählen Sie den Menütyp und klicken Sie auf Neu, um ihn zu erstellen.');
if (!defined('_MENU_CONTENT')) define('_MENU_CONTENT', 'Inhalt');
if (!defined('_MENU_MODULE')) define('_MENU_MODULE', 'Modul');
if (!defined('_MENU_LINK')) define('_MENU_LINK', 'Link');
if (!defined('_MENU_NEW_INSTRUCTION')) define('_MENU_NEW_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_MENU_TARGET')) define('_MENU_TARGET', 'Ziel');
if (!defined('_NONE')) define('_NONE', 'Keine');
if (!defined('_MENU_PARENT')) define('_MENU_PARENT', 'Übergeordnet');
if (!defined('_MENU_MODNAME')) define('_MENU_MODNAME', 'Modul');
if (!defined('_MENU_EDIT_INSTRUCTION')) define('_MENU_EDIT_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_MENU_URL')) define('_MENU_URL', 'URL');
if (!defined('_MENU_NONE')) define('_MENU_NONE', 'Keine');
