<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_MENU_SETTING')) define('_MENU_SETTING', 'Menús');
if (!defined('_MENU_SETTING_INSTRUCTION')) define('_MENU_SETTING_INSTRUCTION', 'Pulsa Nuevo para crear un menú o Volver para regresar a la configuración.');
if (!defined('_MENU_TITLE')) define('_MENU_TITLE', 'Título');
if (!defined('_MENU_TYPE')) define('_MENU_TYPE', 'Tipo');
if (!defined('_MENU_TYPE_INSTRUCTION')) define('_MENU_TYPE_INSTRUCTION', 'Elige el tipo de menú y pulsa Nuevo para crearlo.');
if (!defined('_MENU_CONTENT')) define('_MENU_CONTENT', 'Contenido');
if (!defined('_MENU_MODULE')) define('_MENU_MODULE', 'Módulo');
if (!defined('_MENU_LINK')) define('_MENU_LINK', 'Enlace');
if (!defined('_MENU_NEW_INSTRUCTION')) define('_MENU_NEW_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_MENU_TARGET')) define('_MENU_TARGET', 'Destino');
if (!defined('_NONE')) define('_NONE', 'Ninguno');
if (!defined('_MENU_PARENT')) define('_MENU_PARENT', 'Elemento superior');
if (!defined('_MENU_MODNAME')) define('_MENU_MODNAME', 'Módulo');
if (!defined('_MENU_EDIT_INSTRUCTION')) define('_MENU_EDIT_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_MENU_URL')) define('_MENU_URL', 'URL');
if (!defined('_MENU_NONE')) define('_MENU_NONE', 'Ninguno');
