<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_SETUP_CHARSET')) define('_SETUP_CHARSET', 'UTF-8');
if (!defined('_MENU_SETTING')) define('_MENU_SETTING', 'メニュー設定');
if (!defined('_MENU_SETTING_INSTRUCTION')) define('_MENU_SETTING_INSTRUCTION', '新規を押してメニューを作成するか、戻るを押して設定に戻ります。');
if (!defined('_MENU_TITLE')) define('_MENU_TITLE', 'タイトル');
if (!defined('_MENU_TYPE')) define('_MENU_TYPE', '種類');
if (!defined('_MENU_TYPE_INSTRUCTION')) define('_MENU_TYPE_INSTRUCTION', 'メニューの種類を選び、新規を押して作成してください。');
if (!defined('_MENU_CONTENT')) define('_MENU_CONTENT', 'コンテンツ');
if (!defined('_MENU_MODULE')) define('_MENU_MODULE', 'モジュール');
if (!defined('_MENU_LINK')) define('_MENU_LINK', 'リンク');
if (!defined('_MENU_NEW_INSTRUCTION')) define('_MENU_NEW_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_MENU_TARGET')) define('_MENU_TARGET', 'リンク先');
if (!defined('_NONE')) define('_NONE', 'なし');
if (!defined('_MENU_PARENT')) define('_MENU_PARENT', '親項目');
if (!defined('_MENU_MODNAME')) define('_MENU_MODNAME', 'モジュール');
if (!defined('_MENU_EDIT_INSTRUCTION')) define('_MENU_EDIT_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_MENU_URL')) define('_MENU_URL', 'URL');
if (!defined('_MENU_NONE')) define('_MENU_NONE', 'なし');
