<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_ROLE_SETTING')) define('_ROLE_SETTING', 'ロールと権限');
if (!defined('_ROLE_SETTING_INSTRUCTION')) define('_ROLE_SETTING_INSTRUCTION', '編集者、投稿者、寄稿者などのロールと権限を定義します。メンバー設定でユーザーに割り当ててください。');
if (!defined('_ROLE_TITLE')) define('_ROLE_TITLE', 'ロール名');
if (!defined('_ROLE_CAPABILITIES')) define('_ROLE_CAPABILITIES', '権限');
if (!defined('_ROLE_NEW')) define('_ROLE_NEW', 'ロールを追加');
if (!defined('_ROLE_NEW_INSTRUCTION')) define('_ROLE_NEW_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_ROLE_EDIT')) define('_ROLE_EDIT', 'ロールを編集');
if (!defined('_ROLE_EDIT_INSTRUCTION')) define('_ROLE_EDIT_INSTRUCTION', 'フォームに入力してください。（*）は必須項目です。');
if (!defined('_ROLE_NOT_FOUND')) define('_ROLE_NOT_FOUND', 'ロールが見つかりません');
