<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_ROLE_SETTING')) define('_ROLE_SETTING', 'Rôles et permissions');
if (!defined('_ROLE_SETTING_INSTRUCTION')) define('_ROLE_SETTING_INSTRUCTION', 'Définissez les rôles et permissions, comme éditeur, auteur ou contributeur. Attribuez un rôle depuis les paramètres des membres.');
if (!defined('_ROLE_TITLE')) define('_ROLE_TITLE', 'Nom du rôle');
if (!defined('_ROLE_CAPABILITIES')) define('_ROLE_CAPABILITIES', 'Permissions');
if (!defined('_ROLE_NEW')) define('_ROLE_NEW', 'Nouveau rôle');
if (!defined('_ROLE_NEW_INSTRUCTION')) define('_ROLE_NEW_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_ROLE_EDIT')) define('_ROLE_EDIT', 'Modifier le rôle');
if (!defined('_ROLE_EDIT_INSTRUCTION')) define('_ROLE_EDIT_INSTRUCTION', 'Remplissez le formulaire. Les champs marqués (*) sont obligatoires.');
if (!defined('_ROLE_NOT_FOUND')) define('_ROLE_NOT_FOUND', 'Rôle introuvable');
