<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_ROLE_SETTING')) define('_ROLE_SETTING', 'Roles y permisos');
if (!defined('_ROLE_SETTING_INSTRUCTION')) define('_ROLE_SETTING_INSTRUCTION', 'Define roles y sus permisos, como editor, autor o colaborador. Asigna un rol desde la configuración de miembros.');
if (!defined('_ROLE_TITLE')) define('_ROLE_TITLE', 'Nombre del rol');
if (!defined('_ROLE_CAPABILITIES')) define('_ROLE_CAPABILITIES', 'Permisos');
if (!defined('_ROLE_NEW')) define('_ROLE_NEW', 'Nuevo rol');
if (!defined('_ROLE_NEW_INSTRUCTION')) define('_ROLE_NEW_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_ROLE_EDIT')) define('_ROLE_EDIT', 'Editar rol');
if (!defined('_ROLE_EDIT_INSTRUCTION')) define('_ROLE_EDIT_INSTRUCTION', 'Completa el formulario. Los campos con (*) son obligatorios.');
if (!defined('_ROLE_NOT_FOUND')) define('_ROLE_NOT_FOUND', 'Rol no encontrado');
