<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_ROLE_SETTING')) define('_ROLE_SETTING', 'Rollen und Berechtigungen');
if (!defined('_ROLE_SETTING_INSTRUCTION')) define('_ROLE_SETTING_INSTRUCTION', 'Definieren Sie Rollen und ihre Berechtigungen, etwa Redakteur, Autor oder Mitarbeiter. Weisen Sie Rollen in den Mitgliedseinstellungen zu.');
if (!defined('_ROLE_TITLE')) define('_ROLE_TITLE', 'Rollenname');
if (!defined('_ROLE_CAPABILITIES')) define('_ROLE_CAPABILITIES', 'Berechtigungen');
if (!defined('_ROLE_NEW')) define('_ROLE_NEW', 'Neue Rolle');
if (!defined('_ROLE_NEW_INSTRUCTION')) define('_ROLE_NEW_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_ROLE_EDIT')) define('_ROLE_EDIT', 'Rolle bearbeiten');
if (!defined('_ROLE_EDIT_INSTRUCTION')) define('_ROLE_EDIT_INSTRUCTION', 'Bitte füllen Sie das Formular aus. Felder mit (*) sind erforderlich.');
if (!defined('_ROLE_NOT_FOUND')) define('_ROLE_NOT_FOUND', 'Rolle nicht gefunden');
