<?php
// Generated by language/build-packs.php; edit language/translations.tsv.
if (!defined('_ROLE_SETTING')) define('_ROLE_SETTING', 'Funções e permissões');
if (!defined('_ROLE_SETTING_INSTRUCTION')) define('_ROLE_SETTING_INSTRUCTION', 'Defina funções e permissões, como editor, autor ou colaborador. Atribua uma função nas configurações de membros.');
if (!defined('_ROLE_TITLE')) define('_ROLE_TITLE', 'Nome da função');
if (!defined('_ROLE_CAPABILITIES')) define('_ROLE_CAPABILITIES', 'Permissões');
if (!defined('_ROLE_NEW')) define('_ROLE_NEW', 'Nova função');
if (!defined('_ROLE_NEW_INSTRUCTION')) define('_ROLE_NEW_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_ROLE_EDIT')) define('_ROLE_EDIT', 'Editar função');
if (!defined('_ROLE_EDIT_INSTRUCTION')) define('_ROLE_EDIT_INSTRUCTION', 'Preencha o formulário. Os campos com (*) são obrigatórios.');
if (!defined('_ROLE_NOT_FOUND')) define('_ROLE_NOT_FOUND', 'Função não encontrada');
